-- =============================================================================
-- 107_check_in_reminder_schedule.sql
--
-- DOCUMENTATION ONLY — no live schema or cron changes in this migration.
--
-- The `check-in-reminder` Edge Function emails + notifies community members
-- exactly 3 days before the monthly meeting, when the monthly check-in opens.
-- The function is service-role (verify_jwt = false) and is meant to be invoked
-- once per day by pg_cron via pg_net (net.http_post).
--
-- The schedule below is applied MANUALLY (not through migrations) because it
-- embeds the project ref + service-role key, which must not live in version
-- control. Run the snippet against the database with the real values filled in,
-- using a Supabase Vault secret or a session-local setting for the JWT.
--
-- Timing rationale:
--   - The preview has to reach Nat at 6:00am America/Los_Angeles. Nat, 2026-08-20:
--     *"I want 6am. Whatever the current 6am is."* — so it must not drift an hour
--     when daylight saving ends.
--   - pg_cron evaluates schedules in the database timezone, which is UTC on
--     Supabase, and has no per-job timezone. So the job wakes TWICE, at 13:00 and
--     14:00 UTC, and a `where` clause lets exactly one of them through: whichever
--     one is really 6am in Los Angeles. PDT -> 13:00 UTC. PST -> 14:00 UTC.
--   - The function itself computes "today" and the meeting day in Pacific time
--     (due_date is stored as midnight UTC = 5pm Pacific the prior day, i.e. the
--     real meeting day), so evaluating in the 6am hour lands on the correct
--     calendar day. It is also idempotent (dedups per survey + period via the
--     notifications.metadata marker), so a repeated run the same day is safe.
--
-- Prerequisites (enable once, in the Supabase dashboard or via SQL):
--   create extension if not exists pg_cron;
--   create extension if not exists pg_net;
--
-- Example schedule to apply manually (replace <PROJECT_REF> and the auth token):
--
--   select cron.schedule(
--     'check-in-reminder-daily',
--     '0 13,14 * * *',  -- both candidate hours; the where-clause picks the real 6am
--     $$
--     select net.http_post(
--       url := 'https://<PROJECT_REF>.supabase.co/functions/v1/check-in-reminder',
--       headers := jsonb_build_object(
--         'Content-Type', 'application/json',
--         'apikey', (select decrypted_secret from vault.decrypted_secrets where name = 'service_role_key'),
--         'Authorization', 'Bearer ' || (select decrypted_secret from vault.decrypted_secrets where name = 'service_role_key')
--       ),
--       body := '{}'::jsonb
--     )
--     where extract(hour from (now() at time zone 'America/Los_Angeles')) = 6;
--     $$
--   );
--
-- To update the schedule later, unschedule then reschedule:
--
--   select cron.unschedule('check-in-reminder-daily');
--
-- =============================================================================
