export interface DailyQuestion {
  text: string;
  category: string;
  emoji: string;
}

export const DAILY_QUESTIONS: DailyQuestion[] = [
  // ── FOOD (36) ───────────────────────────────────────────────────────────────
  { text: "What's a meal that makes you feel completely at home?", category: "food", emoji: "🍽️" },
  { text: "If you could only eat one cuisine for a month, what would it be?", category: "food", emoji: "🍽️" },
  { text: "What's the most adventurous food you've ever tried?", category: "food", emoji: "🍽️" },
  { text: "Morning person's breakfast vs. night owl's midnight snack — which are you?", category: "food", emoji: "🍽️" },
  { text: "What dish do you wish you knew how to make?", category: "food", emoji: "🍽️" },
  { text: "Coffee, tea, or neither — and how do you take it?", category: "food", emoji: "🍽️" },
  { text: "What's a food from your childhood you still crave?", category: "food", emoji: "🍽️" },
  { text: "Would you rather be an incredible baker or a masterful chef?", category: "food", emoji: "🍽️" },
  { text: "What's the most underrated ingredient in cooking?", category: "food", emoji: "🍽️" },
  { text: "Describe your perfect dinner party menu in three courses.", category: "food", emoji: "🍽️" },
  { text: "Sweet, salty, spicy, or umami — your dominant food personality?", category: "food", emoji: "🍽️" },
  { text: "What's a food you hated as a kid but love now?", category: "food", emoji: "🍽️" },
  { text: "Best meal you've ever eaten — where and what was it?", category: "food", emoji: "🍽️" },
  { text: "Do you cook to relax or does cooking stress you out?", category: "food", emoji: "🍽️" },
  { text: "What's your go-to meal when you have no energy to think?", category: "food", emoji: "🍽️" },
  { text: "Farm-to-table or world-traveled flavors — what excites you more?", category: "food", emoji: "🍽️" },
  { text: "What's one food you think everyone should try before they die?", category: "food", emoji: "🍽️" },
  { text: "If your cooking style were a country, what country would it be?", category: "food", emoji: "🍽️" },
  { text: "What's the last recipe you saved but haven't made yet?", category: "food", emoji: "🍽️" },
  { text: "Leftovers: love them or hate them?", category: "food", emoji: "🍽️" },
  { text: "What's your relationship with food at social events?", category: "food", emoji: "🍽️" },
  { text: "If you could eat anywhere in the world tonight, where would it be?", category: "food", emoji: "🍽️" },
  { text: "What ingredient do you always have in your fridge?", category: "food", emoji: "🍽️" },
  { text: "Do you follow recipes or freestyle in the kitchen?", category: "food", emoji: "🍽️" },
  { text: "What's a food trend you think is overrated?", category: "food", emoji: "🍽️" },
  { text: "What's your ultimate comfort food?", category: "food", emoji: "🍽️" },
  { text: "What's something you eat that surprises people?", category: "food", emoji: "🍽️" },
  { text: "Describe the perfect Sunday brunch.", category: "food", emoji: "🍽️" },
  { text: "What's a food memory tied to a specific person in your life?", category: "food", emoji: "🍽️" },
  { text: "If you had to give up one food forever, what would hurt the least?", category: "food", emoji: "🍽️" },
  { text: "What's a dish you make better than any restaurant?", category: "food", emoji: "🍽️" },
  { text: "Cooking for one vs. cooking for a crowd — which do you prefer?", category: "food", emoji: "🍽️" },
  { text: "What's the most effort you've ever put into a meal?", category: "food", emoji: "🍽️" },
  { text: "What food do you wish you liked but just can't get behind?", category: "food", emoji: "🍽️" },
  { text: "If you could instantly master one cooking technique, what would it be?", category: "food", emoji: "🍽️" },
  { text: "What's your relationship with dessert?", category: "food", emoji: "🍽️" },

  // ── CREATIVITY (36) ─────────────────────────────────────────────────────────
  { text: "What creative pursuit have you abandoned that you miss?", category: "creativity", emoji: "🎨" },
  { text: "Where do your best ideas tend to come from?", category: "creativity", emoji: "🎨" },
  { text: "Do you create for yourself, for others, or for the work itself?", category: "creativity", emoji: "🎨" },
  { text: "What medium would you explore if you had unlimited time?", category: "creativity", emoji: "🎨" },
  { text: "Describe a piece of art, music, or writing that changed how you see things.", category: "creativity", emoji: "🎨" },
  { text: "Are you more energized by starting something new or finishing something old?", category: "creativity", emoji: "🎨" },
  { text: "What does your creative process look like when it's flowing?", category: "creativity", emoji: "🎨" },
  { text: "What does your creative process look like when it's stuck?", category: "creativity", emoji: "🎨" },
  { text: "Do you prefer making things alone or collaborating?", category: "creativity", emoji: "🎨" },
  { text: "What creative skill do you wish you'd developed earlier?", category: "creativity", emoji: "🎨" },
  { text: "What's the last thing you made that you were genuinely proud of?", category: "creativity", emoji: "🎨" },
  { text: "How do you know when something you've created is done?", category: "creativity", emoji: "🎨" },
  { text: "What would you make if you knew no one would ever see it?", category: "creativity", emoji: "🎨" },
  { text: "Are you more drawn to minimalism or maximalism?", category: "creativity", emoji: "🎨" },
  { text: "What's a creative field you deeply admire but couldn't do yourself?", category: "creativity", emoji: "🎨" },
  { text: "What does creativity mean to you outside of traditional 'art'?", category: "creativity", emoji: "🎨" },
  { text: "Do you have a creative ritual or routine?", category: "creativity", emoji: "🎨" },
  { text: "What's the most creative decision you've ever made in your daily life?", category: "creativity", emoji: "🎨" },
  { text: "If your life were a visual aesthetic, what would it look like?", category: "creativity", emoji: "🎨" },
  { text: "What's something you've created that surprised even you?", category: "creativity", emoji: "🎨" },
  { text: "How has your creative taste evolved in the last 5 years?", category: "creativity", emoji: "🎨" },
  { text: "Do you think creativity can be learned or is it innate?", category: "creativity", emoji: "🎨" },
  { text: "What's an unconventional thing you find beautiful?", category: "creativity", emoji: "🎨" },
  { text: "What creative project have you been putting off?", category: "creativity", emoji: "🎨" },
  { text: "Music while you work — yes, no, or it depends?", category: "creativity", emoji: "🎨" },
  { text: "What's the most creative space you've ever been in?", category: "creativity", emoji: "🎨" },
  { text: "What do you think is the most overlooked form of creativity?", category: "creativity", emoji: "🎨" },
  { text: "If you could live inside one work of fiction, what would it be?", category: "creativity", emoji: "🎨" },
  { text: "What's something you've repurposed in a creative way?", category: "creativity", emoji: "🎨" },
  { text: "Do you have a signature style — in anything?", category: "creativity", emoji: "🎨" },
  { text: "What's the difference between craft and art to you?", category: "creativity", emoji: "🎨" },
  { text: "What creative project would you fund if money were no object?", category: "creativity", emoji: "🎨" },
  { text: "Who is the most creatively inspiring person you know personally?", category: "creativity", emoji: "🎨" },
  { text: "Is there a color that represents your current season of life?", category: "creativity", emoji: "🎨" },
  { text: "What would you make if you had one month and no responsibilities?", category: "creativity", emoji: "🎨" },
  { text: "Where do you feel most creatively alive?", category: "creativity", emoji: "🎨" },

  // ── INNER LIFE (36) ──────────────────────────────────────────────────────────
  { text: "What do you believe happens after we die?", category: "inner life", emoji: "✨" },
  { text: "How do you connect with something larger than yourself?", category: "inner life", emoji: "✨" },
  { text: "Do you have a daily practice that grounds you?", category: "inner life", emoji: "✨" },
  { text: "What's a question you come back to again and again?", category: "inner life", emoji: "✨" },
  { text: "When do you feel most at peace?", category: "inner life", emoji: "✨" },
  { text: "What does 'home' mean to you at a soul level?", category: "inner life", emoji: "✨" },
  { text: "What's the most meaningful conversation you've ever had?", category: "inner life", emoji: "✨" },
  { text: "Do you believe things happen for a reason?", category: "inner life", emoji: "✨" },
  { text: "What has grief taught you?", category: "inner life", emoji: "✨" },
  { text: "How has your sense of purpose shifted in the last decade?", category: "inner life", emoji: "✨" },
  { text: "What does it feel like when you're living in alignment?", category: "inner life", emoji: "✨" },
  { text: "What's a belief you hold that you've never said out loud?", category: "inner life", emoji: "✨" },
  { text: "How do you handle the unknown?", category: "inner life", emoji: "✨" },
  { text: "What do you think is the meaning of a good life?", category: "inner life", emoji: "✨" },
  { text: "When did you last feel truly seen?", category: "inner life", emoji: "✨" },
  { text: "What's a spiritual or philosophical idea that changed you?", category: "inner life", emoji: "✨" },
  { text: "How do you define the difference between intuition and fear?", category: "inner life", emoji: "✨" },
  { text: "What do you think your soul needs most right now?", category: "inner life", emoji: "✨" },
  { text: "Do you believe in luck, destiny, or something else?", category: "inner life", emoji: "✨" },
  { text: "What does forgiveness mean to you in practice?", category: "inner life", emoji: "✨" },
  { text: "What's something you've had to unlearn?", category: "inner life", emoji: "✨" },
  { text: "When do you feel most connected to other people?", category: "inner life", emoji: "✨" },
  { text: "What's a value you refuse to compromise on?", category: "inner life", emoji: "✨" },
  { text: "How do you find meaning in ordinary moments?", category: "inner life", emoji: "✨" },
  { text: "What does it mean to live with integrity?", category: "inner life", emoji: "✨" },
  { text: "What have you changed your mind about most significantly?", category: "inner life", emoji: "✨" },
  { text: "What's the kindest thing anyone has ever done for you?", category: "inner life", emoji: "✨" },
  { text: "How do you define success for yourself, not anyone else?", category: "inner life", emoji: "✨" },
  { text: "What's the most important thing you want to pass on to others?", category: "inner life", emoji: "✨" },
  { text: "What does healing look like for you?", category: "inner life", emoji: "✨" },
  { text: "What's a moment that cracked you open in the best way?", category: "inner life", emoji: "✨" },
  { text: "Where do you find wisdom?", category: "inner life", emoji: "✨" },
  { text: "What's something you believe now that your younger self would be surprised by?", category: "inner life", emoji: "✨" },
  { text: "When do you feel most fully yourself?", category: "inner life", emoji: "✨" },
  { text: "What does enough feel like to you?", category: "inner life", emoji: "✨" },
  { text: "What do you think is the biggest illusion most people live under?", category: "inner life", emoji: "✨" },

  // ── AMBITION (36) ────────────────────────────────────────────────────────────
  { text: "What's the work you were made to do?", category: "ambition", emoji: "🚀" },
  { text: "What would you pursue if failure weren't possible?", category: "ambition", emoji: "🚀" },
  { text: "What's the most important project you've ever abandoned?", category: "ambition", emoji: "🚀" },
  { text: "How do you define professional success for yourself right now?", category: "ambition", emoji: "🚀" },
  { text: "What's something you've built that you're quietly proud of?", category: "ambition", emoji: "🚀" },
  { text: "Where do you want to be in your work in 3 years?", category: "ambition", emoji: "🚀" },
  { text: "What does 'doing good work' mean to you?", category: "ambition", emoji: "🚀" },
  { text: "What's a skill gap you're actively trying to close?", category: "ambition", emoji: "🚀" },
  { text: "Who is your biggest professional inspiration and why?", category: "ambition", emoji: "🚀" },
  { text: "What's the hardest professional decision you've ever made?", category: "ambition", emoji: "🚀" },
  { text: "What energizes you most in your work?", category: "ambition", emoji: "🚀" },
  { text: "What drains you fastest in your work?", category: "ambition", emoji: "🚀" },
  { text: "What's something you've been meaning to start for more than a year?", category: "ambition", emoji: "🚀" },
  { text: "How do you know when it's time to pivot versus persist?", category: "ambition", emoji: "🚀" },
  { text: "What's a dream you've talked yourself out of?", category: "ambition", emoji: "🚀" },
  { text: "What's the biggest professional risk you've ever taken?", category: "ambition", emoji: "🚀" },
  { text: "What would make your work feel more meaningful?", category: "ambition", emoji: "🚀" },
  { text: "If you could collaborate with anyone on any project, what would it be?", category: "ambition", emoji: "🚀" },
  { text: "What's a problem in the world you wish you were solving?", category: "ambition", emoji: "🚀" },
  { text: "How do you measure impact in what you do?", category: "ambition", emoji: "🚀" },
  { text: "What does your ideal work environment feel like?", category: "ambition", emoji: "🚀" },
  { text: "What's something no one taught you about work that you had to learn yourself?", category: "ambition", emoji: "🚀" },
  { text: "What's the most important lesson from a professional failure?", category: "ambition", emoji: "🚀" },
  { text: "How do you stay motivated when a project gets hard?", category: "ambition", emoji: "🚀" },
  { text: "What's an industry outside yours that you find fascinating?", category: "ambition", emoji: "🚀" },
  { text: "What's one thing you'd change about the culture of your field?", category: "ambition", emoji: "🚀" },
  { text: "If money weren't a factor, what would your days look like?", category: "ambition", emoji: "🚀" },
  { text: "What kind of leader do you aspire to be — or work for?", category: "ambition", emoji: "🚀" },
  { text: "What's a professional goal you've been keeping quietly?", category: "ambition", emoji: "🚀" },
  { text: "How do you handle competition?", category: "ambition", emoji: "🚀" },
  { text: "What's a business idea you've had but never pursued?", category: "ambition", emoji: "🚀" },
  { text: "What's the best professional advice you've ever received?", category: "ambition", emoji: "🚀" },
  { text: "What does work-life integration look like at its best for you?", category: "ambition", emoji: "🚀" },
  { text: "What's something you're currently building that excites you?", category: "ambition", emoji: "🚀" },
  { text: "How do you decide what's worth your time?", category: "ambition", emoji: "🚀" },
  { text: "What legacy do you want your work to leave?", category: "ambition", emoji: "🚀" },

  // ── LIFESTYLE (36) ───────────────────────────────────────────────────────────
  { text: "What's your morning like at its best?", category: "lifestyle", emoji: "🌿" },
  { text: "What habit would change everything if you could make it stick?", category: "lifestyle", emoji: "🌿" },
  { text: "What does a perfect day off look like for you?", category: "lifestyle", emoji: "🌿" },
  { text: "Are you a homebody, an adventurer, or something in between?", category: "lifestyle", emoji: "🌿" },
  { text: "What's a small ritual that means a lot to you?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you decompress after a hard day?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something you do every day that brings you joy?", category: "lifestyle", emoji: "🌿" },
  { text: "Night owl or early bird — and have you always been this way?", category: "lifestyle", emoji: "🌿" },
  { text: "What's your relationship with your phone?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you like to spend a free Sunday?", category: "lifestyle", emoji: "🌿" },
  { text: "What's a habit you've successfully built in the last year?", category: "lifestyle", emoji: "🌿" },
  { text: "What's your go-to way to reset when you're overwhelmed?", category: "lifestyle", emoji: "🌿" },
  { text: "What does a productive day feel like in your body?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something in your environment that makes you feel good?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you approach saying no?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something you've simplified in your life that was a great decision?", category: "lifestyle", emoji: "🌿" },
  { text: "What's a lifestyle change you've been considering?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you handle transitions — between tasks, seasons, chapters?", category: "lifestyle", emoji: "🌿" },
  { text: "What does rest actually look like for you?", category: "lifestyle", emoji: "🌿" },
  { text: "What's your relationship with structure and spontaneity?", category: "lifestyle", emoji: "🌿" },
  { text: "What's the first thing you notice when you walk into someone's home?", category: "lifestyle", emoji: "🌿" },
  { text: "What's a place you return to again and again?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you stay curious?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something you want more of in your everyday life?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something you've intentionally cut out?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you make decisions?", category: "lifestyle", emoji: "🌿" },
  { text: "What's your relationship with solitude?", category: "lifestyle", emoji: "🌿" },
  { text: "What would you do with an extra hour every day?", category: "lifestyle", emoji: "🌿" },
  { text: "What's the most underrated self-care practice?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you celebrate small wins?", category: "lifestyle", emoji: "🌿" },
  { text: "What's a daily pleasure you protect fiercely?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something that used to feel important but doesn't anymore?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you stay organized — or do you?", category: "lifestyle", emoji: "🌿" },
  { text: "What's a lifestyle aspiration you're actively working toward?", category: "lifestyle", emoji: "🌿" },
  { text: "How do you decide what deserves your energy?", category: "lifestyle", emoji: "🌿" },
  { text: "What's something you're practicing being more intentional about?", category: "lifestyle", emoji: "🌿" },

  // ── RELATIONSHIPS (36) ───────────────────────────────────────────────────────
  { text: "What's something you wish you could tell a younger version of yourself about relationships?", category: "relationships", emoji: "❤️" },
  { text: "How do you show love most naturally?", category: "relationships", emoji: "❤️" },
  { text: "What do you need most from a close friendship?", category: "relationships", emoji: "❤️" },
  { text: "How has your relationship with community changed over time?", category: "relationships", emoji: "❤️" },
  { text: "What's a friendship you're grateful for that surprised you?", category: "relationships", emoji: "❤️" },
  { text: "How do you repair a relationship when something's gone wrong?", category: "relationships", emoji: "❤️" },
  { text: "What's something a mentor or elder taught you that stuck?", category: "relationships", emoji: "❤️" },
  { text: "What's the quality you most look for in a collaborator?", category: "relationships", emoji: "❤️" },
  { text: "What's something you wish people understood about you?", category: "relationships", emoji: "❤️" },
  { text: "How do you know when you've found your people?", category: "relationships", emoji: "❤️" },
  { text: "What's the most generous thing someone has done for you?", category: "relationships", emoji: "❤️" },
  { text: "What does showing up for someone look like to you?", category: "relationships", emoji: "❤️" },
  { text: "Who in your life challenges you to be better?", category: "relationships", emoji: "❤️" },
  { text: "What's a relationship that shaped who you are today?", category: "relationships", emoji: "❤️" },
  { text: "How do you handle conflict with people you care about?", category: "relationships", emoji: "❤️" },
  { text: "What does trust look like in a friendship or partnership?", category: "relationships", emoji: "❤️" },
  { text: "What's something you've learned about yourself through a difficult relationship?", category: "relationships", emoji: "❤️" },
  { text: "What's a boundary you're proud of having set?", category: "relationships", emoji: "❤️" },
  { text: "How do you stay connected with people across distance?", category: "relationships", emoji: "❤️" },
  { text: "What's the role of community in a good life?", category: "relationships", emoji: "❤️" },
  { text: "Who do you turn to when things get hard?", category: "relationships", emoji: "❤️" },
  { text: "What's something you love to do for other people?", category: "relationships", emoji: "❤️" },
  { text: "What's a relationship dynamic you've actively tried to change?", category: "relationships", emoji: "❤️" },
  { text: "How do you balance independence with deep connection?", category: "relationships", emoji: "❤️" },
  { text: "What's something you've learned from a friendship that ended?", category: "relationships", emoji: "❤️" },
  { text: "What do you think makes a community actually work?", category: "relationships", emoji: "❤️" },
  { text: "What's a kind of love you're still learning how to receive?", category: "relationships", emoji: "❤️" },
  { text: "How do you invest in the people you care about?", category: "relationships", emoji: "❤️" },
  { text: "What makes someone feel like family to you?", category: "relationships", emoji: "❤️" },
  { text: "How do you express appreciation to the people in your life?", category: "relationships", emoji: "❤️" },
  { text: "What kind of friend do you want to be known as?", category: "relationships", emoji: "❤️" },
  { text: "What role do you usually play in a group dynamic?", category: "relationships", emoji: "❤️" },
  { text: "What's a relationship goal you're working toward?", category: "relationships", emoji: "❤️" },
  { text: "What does belonging mean to you?", category: "relationships", emoji: "❤️" },
  { text: "What's something you admire about how someone in your life loves people?", category: "relationships", emoji: "❤️" },
  { text: "How do you balance giving and receiving in relationships?", category: "relationships", emoji: "❤️" },

  // ── FUN (36) ─────────────────────────────────────────────────────────────────
  { text: "What's a hidden talent you have that would surprise people?", category: "fun", emoji: "😄" },
  { text: "What's your go-to karaoke song?", category: "fun", emoji: "😄" },
  { text: "If you had a theme song for your life right now, what would it be?", category: "fun", emoji: "😄" },
  { text: "What movie could you watch on repeat forever?", category: "fun", emoji: "😄" },
  { text: "What's a completely irrational fear you have?", category: "fun", emoji: "😄" },
  { text: "What reality TV show would you most want to be on?", category: "fun", emoji: "😄" },
  { text: "What's the funniest thing that's happened to you recently?", category: "fun", emoji: "😄" },
  { text: "What's your most controversial food opinion?", category: "fun", emoji: "😄" },
  { text: "If you could have dinner with any 3 people (living or dead), who would you pick?", category: "fun", emoji: "😄" },
  { text: "What's something you're inexplicably good at?", category: "fun", emoji: "😄" },
  { text: "What's the weirdest job you've ever had or considered?", category: "fun", emoji: "😄" },
  { text: "If you could live in any decade, which would you choose?", category: "fun", emoji: "😄" },
  { text: "What skill do you have that seems completely useless but you love?", category: "fun", emoji: "😄" },
  { text: "What's the most embarrassing thing you're also proud of?", category: "fun", emoji: "😄" },
  { text: "If you could only watch one genre of movies forever, what would it be?", category: "fun", emoji: "😄" },
  { text: "What's the strangest hobby you've ever had?", category: "fun", emoji: "😄" },
  { text: "What fictional universe would you most want to live in?", category: "fun", emoji: "😄" },
  { text: "What's your most controversial opinion about pop culture?", category: "fun", emoji: "😄" },
  { text: "What's something you've done that sounded crazy but worked out?", category: "fun", emoji: "😄" },
  { text: "What's the last thing that made you laugh until you cried?", category: "fun", emoji: "😄" },
  { text: "What's your spirit animal and why?", category: "fun", emoji: "😄" },
  { text: "If you woke up tomorrow as someone else for a day, who would you choose?", category: "fun", emoji: "😄" },
  { text: "What's the most extra thing you've done for something you love?", category: "fun", emoji: "😄" },
  { text: "What game are you weirdly competitive about?", category: "fun", emoji: "😄" },
  { text: "What's a movie or show you're embarrassed to admit you love?", category: "fun", emoji: "😄" },
  { text: "If you wrote a memoir, what would the title be?", category: "fun", emoji: "😄" },
  { text: "If you could only listen to one artist for a year, who would it be?", category: "fun", emoji: "😄" },
  { text: "What's something about you that contradicts your personality?", category: "fun", emoji: "😄" },
  { text: "What's a trend you fully embraced that you now cringe at?", category: "fun", emoji: "😄" },
  { text: "What would your signature cocktail or mocktail be?", category: "fun", emoji: "😄" },
  { text: "What's a compliment you've received that you still think about?", category: "fun", emoji: "😄" },
  { text: "If you had a warning label, what would it say?", category: "fun", emoji: "😄" },
  { text: "What's something you can't do that most people can?", category: "fun", emoji: "😄" },
  { text: "What would your perfect lazy day look like in embarrassing detail?", category: "fun", emoji: "😄" },
  { text: "What's an inside joke that defines a friendship?", category: "fun", emoji: "😄" },
  { text: "What's the most creative excuse you've ever made?", category: "fun", emoji: "😄" },

  // ── LEARNING (36) ────────────────────────────────────────────────────────────
  { text: "What's something you've been learning lately that's changing how you think?", category: "learning", emoji: "📚" },
  { text: "What's the most important lesson a failure taught you?", category: "learning", emoji: "📚" },
  { text: "What skill do you wish you'd learned in school but didn't?", category: "learning", emoji: "📚" },
  { text: "How do you learn best — reading, doing, watching, or talking?", category: "learning", emoji: "📚" },
  { text: "What's a book that fundamentally changed you?", category: "learning", emoji: "📚" },
  { text: "What's something you thought you understood until you had to explain it?", category: "learning", emoji: "📚" },
  { text: "What are you currently trying to get better at?", category: "learning", emoji: "📚" },
  { text: "How has your definition of intelligence evolved?", category: "learning", emoji: "📚" },
  { text: "What's a subject you'd go back to school for if it were free and easy?", category: "learning", emoji: "📚" },
  { text: "What's something you've had to teach yourself completely from scratch?", category: "learning", emoji: "📚" },
  { text: "Who's been a mentor to you — formal or informal?", category: "learning", emoji: "📚" },
  { text: "How do you handle being a beginner at something?", category: "learning", emoji: "📚" },
  { text: "What's the most interesting thing you've learned in the last month?", category: "learning", emoji: "📚" },
  { text: "What's a belief you held for years that you've since abandoned?", category: "learning", emoji: "📚" },
  { text: "What's the gap between who you are and who you want to be?", category: "learning", emoji: "📚" },
  { text: "What does personal growth look like for you right now?", category: "learning", emoji: "📚" },
  { text: "What's a skill you've mastered that took longer than you expected?", category: "learning", emoji: "📚" },
  { text: "What's something you keep circling back to learn more about?", category: "learning", emoji: "📚" },
  { text: "How do you stay curious as you get older?", category: "learning", emoji: "📚" },
  { text: "What's a class, workshop, or course that surprised you?", category: "learning", emoji: "📚" },
  { text: "What's something your parents taught you, intended or not?", category: "learning", emoji: "📚" },
  { text: "What's a hard truth you had to learn the hard way?", category: "learning", emoji: "📚" },
  { text: "What's the most useful piece of advice you've ever followed?", category: "learning", emoji: "📚" },
  { text: "What's something you know now that would have helped you 10 years ago?", category: "learning", emoji: "📚" },
  { text: "How do you know when you've grown?", category: "learning", emoji: "📚" },
  { text: "What's a habit of mind you're trying to develop?", category: "learning", emoji: "📚" },
  { text: "What do you wish more people understood about learning?", category: "learning", emoji: "📚" },
  { text: "What's something you've learned from someone much younger than you?", category: "learning", emoji: "📚" },
  { text: "What's something you've learned from someone much older than you?", category: "learning", emoji: "📚" },
  { text: "How do you deal with information overload?", category: "learning", emoji: "📚" },
  { text: "What's a subject you could talk about for hours?", category: "learning", emoji: "📚" },
  { text: "What's something you've learned about how you deal with stress?", category: "learning", emoji: "📚" },
  { text: "What's a piece of conventional wisdom you've rejected?", category: "learning", emoji: "📚" },
  { text: "What's a question you've been sitting with for a long time?", category: "learning", emoji: "📚" },
  { text: "What's something you're unlearning?", category: "learning", emoji: "📚" },
  { text: "What's something you want to dedicate serious time to learning this year?", category: "learning", emoji: "📚" },

  // ── HOME & PLACE (36) ────────────────────────────────────────────────────────
  { text: "What does your ideal home feel like?", category: "home", emoji: "🏠" },
  { text: "What's something in your current space that makes you happy every day?", category: "home", emoji: "🏠" },
  { text: "City, suburb, or nature — and does where you live reflect who you are?", category: "home", emoji: "🏠" },
  { text: "What's the first thing you notice when you walk into a space?", category: "home", emoji: "🏠" },
  { text: "What era of design speaks to you most?", category: "home", emoji: "🏠" },
  { text: "What's something you've done to personalize your home that you love?", category: "home", emoji: "🏠" },
  { text: "What would your dream home look like in one sentence?", category: "home", emoji: "🏠" },
  { text: "How important is your environment to your mood?", category: "home", emoji: "🏠" },
  { text: "What's something you've decluttered that freed something in you?", category: "home", emoji: "🏠" },
  { text: "How do you make a new space feel like yours?", category: "home", emoji: "🏠" },
  { text: "What's a texture, material, or element you're drawn to?", category: "home", emoji: "🏠" },
  { text: "What does your desk or workspace say about you?", category: "home", emoji: "🏠" },
  { text: "What's a place outside your home that feels like a sanctuary?", category: "home", emoji: "🏠" },
  { text: "What's something in your home with a great story behind it?", category: "home", emoji: "🏠" },
  { text: "How does nature factor into how you live?", category: "home", emoji: "🏠" },
  { text: "What's the most beautiful space you've ever been in?", category: "home", emoji: "🏠" },
  { text: "What's something you'd splurge on for your home?", category: "home", emoji: "🏠" },
  { text: "What's something you'd never compromise on in a living space?", category: "home", emoji: "🏠" },
  { text: "What would your ideal neighborhood look like?", category: "home", emoji: "🏠" },
  { text: "How do you feel about the city or town you live in?", category: "home", emoji: "🏠" },
  { text: "What's a home project you've been meaning to tackle?", category: "home", emoji: "🏠" },
  { text: "What season does your home feel most alive?", category: "home", emoji: "🏠" },
  { text: "What scent makes a space feel like home to you?", category: "home", emoji: "🏠" },
  { text: "If you could live anywhere in the world for one year, where would it be?", category: "home", emoji: "🏠" },
  { text: "What type of travel genuinely restores you?", category: "home", emoji: "🏠" },
  { text: "Mountains, ocean, desert, or forest — and why?", category: "home", emoji: "🏠" },
  { text: "What part of the world feels inexplicably like 'yours'?", category: "home", emoji: "🏠" },
  { text: "What's somewhere you've visited that surprised you?", category: "home", emoji: "🏠" },
  { text: "What's somewhere you've always wanted to go?", category: "home", emoji: "🏠" },
  { text: "How do you feel about minimalism vs. living surrounded by things you love?", category: "home", emoji: "🏠" },
  { text: "What's something about where you grew up that still shapes you?", category: "home", emoji: "🏠" },
  { text: "What's your relationship with your neighbors — do you want one?", category: "home", emoji: "🏠" },
  { text: "What's something about your city you wish more people appreciated?", category: "home", emoji: "🏠" },
  { text: "Where in the world do you feel most like yourself?", category: "home", emoji: "🏠" },
  { text: "What does your environment tell people about your values?", category: "home", emoji: "🏠" },
  { text: "What's a neighborhood or town that felt like a past life?", category: "home", emoji: "🏠" },

  // ── WELLNESS (36) ────────────────────────────────────────────────────────────
  { text: "What does feeling truly well feel like in your body?", category: "wellness", emoji: "💪" },
  { text: "What's your relationship with sleep?", category: "wellness", emoji: "💪" },
  { text: "How do you handle stress when it builds up?", category: "wellness", emoji: "💪" },
  { text: "What's something that used to drain your health that you've changed?", category: "wellness", emoji: "💪" },
  { text: "What's a physical practice that keeps you sane?", category: "wellness", emoji: "💪" },
  { text: "What does your body need that your mind often resists?", category: "wellness", emoji: "💪" },
  { text: "How do you know when you need to slow down?", category: "wellness", emoji: "💪" },
  { text: "What's your relationship with rest vs. productivity?", category: "wellness", emoji: "💪" },
  { text: "What's something you've done for your health that surprised you?", category: "wellness", emoji: "💪" },
  { text: "What's your earliest health habit — good or bad?", category: "wellness", emoji: "💪" },
  { text: "How do you handle seasons of low energy?", category: "wellness", emoji: "💪" },
  { text: "What's the most sustainable wellness practice you've maintained?", category: "wellness", emoji: "💪" },
  { text: "What does movement look like for you at its best?", category: "wellness", emoji: "💪" },
  { text: "How do you nourish yourself emotionally?", category: "wellness", emoji: "💪" },
  { text: "What's something you do that's good for you that you actually enjoy?", category: "wellness", emoji: "💪" },
  { text: "How has your approach to health changed as you've gotten older?", category: "wellness", emoji: "💪" },
  { text: "What's something that restored your health — physical, mental, or spiritual?", category: "wellness", emoji: "💪" },
  { text: "What does a healthy morning set you up for?", category: "wellness", emoji: "💪" },
  { text: "What's something in your wellness routine that's non-negotiable?", category: "wellness", emoji: "💪" },
  { text: "What's a health belief you've changed your mind about?", category: "wellness", emoji: "💪" },
  { text: "How do you care for your mental health on hard days?", category: "wellness", emoji: "💪" },
  { text: "What's the relationship between your physical and emotional wellbeing?", category: "wellness", emoji: "💪" },
  { text: "What does healing feel like in your experience?", category: "wellness", emoji: "💪" },
  { text: "What's something about wellness culture you find frustrating?", category: "wellness", emoji: "💪" },
  { text: "How do you show your body appreciation?", category: "wellness", emoji: "💪" },
  { text: "What's the most restorative thing you've done in the last year?", category: "wellness", emoji: "💪" },
  { text: "What's something small that makes a big difference to your health?", category: "wellness", emoji: "💪" },
  { text: "How do you handle illness — physical or emotional — with grace?", category: "wellness", emoji: "💪" },
  { text: "What role does community play in your health?", category: "wellness", emoji: "💪" },
  { text: "What's a wellness practice you've been meaning to try?", category: "wellness", emoji: "💪" },
  { text: "What does thriving look like for you, not just surviving?", category: "wellness", emoji: "💪" },
  { text: "How do you balance pushing yourself and protecting yourself?", category: "wellness", emoji: "💪" },
  { text: "What's something you've learned about your nervous system?", category: "wellness", emoji: "💪" },
  { text: "What's a physical sensation that signals you're doing well?", category: "wellness", emoji: "💪" },
  { text: "What's your relationship with aging?", category: "wellness", emoji: "💪" },
  { text: "What's your relationship with your body image?", category: "wellness", emoji: "💪" },
];

/** Returns the same question for everyone on a given calendar day. */
export function getTodayQuestion(): { question: DailyQuestion; index: number } {
  const epoch = new Date(2025, 0, 1); // Jan 1 2025
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const daysSince = Math.floor((today.getTime() - epoch.getTime()) / 86_400_000);
  const index = ((daysSince % DAILY_QUESTIONS.length) + DAILY_QUESTIONS.length) % DAILY_QUESTIONS.length;
  return { question: DAILY_QUESTIONS[index], index };
}
