import type { DailyQuestion } from './dailyQuestions';

/**
 * Production HIVE's deck — 365 questions, one for every day of the year.
 *
 * Nat's call (2026-08-12): every HIVE gets its own full deck so a person in
 * two HIVEs is never asked the same question twice, and this one is "all show,
 * performing, leadership, style, management related." Production HIVE is a
 * small community of live-show people — circus, aerial, stage, the folks who
 * run crews and the folks who fly over them — so the whole deck lives in that
 * world: pre-show rituals and nerves, reading a house, rigging and trust,
 * costumes, running a company, the money side, applause, and what it costs
 * and gives to do this work.
 *
 * The questions look small on purpose. Answers to "what is the smallest
 * audience you'd still give everything to?" quietly show who performs for
 * love, who performs for scale, who leads from calm and who leads from fire —
 * so members find the people who work like them and the people who think
 * opposite, and both matter. Some questions carry echoes of the shelf that
 * flavored Tech's deck — Five Dysfunctions (trust, conflict, commitment),
 * Thinking Fast and Slow (gut versus deliberate), The Tipping Point
 * (connectors and word of mouth) — worn as stage clothes, never as homework.
 *
 * `themes` come from the short shared list in `questionThemes.ts`; they are
 * what lets an answer here match an answer to a totally different question in
 * another HIVE. Append new prompts instead of reordering — saved answers
 * store question_index, so moving older prompts would scramble histories.
 */
export const PRODUCTION_DAILY_QUESTIONS: DailyQuestion[] = [
  { text: 'What is the last thing you do before you step out, every single time?', category: 'pre-show ritual', emoji: '🎭', themes: ['ritual', 'comfort'] },
  { text: 'Where do your nerves live in your body, and what calms them?', category: 'nerves', emoji: '🫀', themes: ['comfort', 'identity'] },
  { text: 'Would you rather be alone or with people in the hour before a show?', category: 'the hour before', emoji: '⏳', themes: ['ritual', 'boundaries'] },
  { text: "What backstage superstition do you respect even if you don't believe it?", category: 'superstition', emoji: '🐇', themes: ['ritual', 'humour'] },
  { text: 'What do you refuse to change on show day?', category: 'show day rules', emoji: '📋', themes: ['ritual', 'boundaries'] },
  { text: 'What does your five-minutes-to-places self need most?', category: 'five to places', emoji: '⏰', themes: ['comfort', 'identity'] },
  { text: 'What music gets you into performance mode?', category: 'warm-up soundtrack', emoji: '🎧', themes: ['ritual', 'comfort'] },
  { text: 'Do you peek at the audience before a show, or never look?', category: 'the peek', emoji: '👀', themes: ['ritual', 'courage'] },
  { text: 'What is a warm-up you do even when nobody is making you?', category: 'warm-up', emoji: '🤸', themes: ['ritual', 'craft'] },
  { text: 'What is your tell that the nerves are the good kind?', category: 'good nerves', emoji: '⚡', themes: ['identity', 'courage'] },
  { text: 'What would you put in a backstage survival kit with only five things?', category: 'survival kit', emoji: '🧰', themes: ['comfort', 'ritual'] },
  { text: 'How early do you like to arrive at the venue, honestly?', category: 'call time', emoji: '🕐', themes: ['ritual', 'identity'] },
  { text: 'What do you say to a castmate who is spiraling at half hour?', category: 'half hour', emoji: '🫶', themes: ['generosity', 'connection'] },
  { text: 'What is a pre-show meal that has never let you down?', category: 'pre-show meal', emoji: '🍌', themes: ['food', 'ritual'] },
  { text: 'When did nerves ever actually help you?', category: 'nerves as fuel', emoji: '🔥', themes: ['courage', 'memory'] },
  { text: 'What do you want said to you right before you go on?', category: 'send-off words', emoji: '💬', themes: ['connection', 'comfort'] },
  { text: 'Quiet backstage or loud backstage — which one is yours?', category: 'backstage volume', emoji: '🔇', themes: ['identity', 'boundaries'] },
  { text: 'What is the strangest thing that has ever calmed you down before a show?', category: 'strange calm', emoji: '🪄', themes: ['comfort', 'humour'] },
  { text: "What is the smallest audience you'd still give everything to?", category: 'smallest audience', emoji: '🕯️', themes: ['values', 'craft'] },
  { text: 'Can you feel the difference between a warm house and a cold one before the first laugh?', category: 'reading the house', emoji: '🌡️', themes: ['connection', 'craft'] },
  { text: "What do you do when the audience isn't with you yet?", category: 'winning the room', emoji: '🎣', themes: ['craft', 'courage'] },
  { text: 'Would you rather perform for a thousand strangers or twelve people you love?', category: "who's out there", emoji: '👥', themes: ['connection', 'courage'] },
  { text: 'What moment in a show do you perform just for yourself?', category: 'for me', emoji: '🤫', themes: ['identity', 'play'] },
  { text: 'What is the best sound an audience can make besides applause?', category: 'audience sounds', emoji: '👂', themes: ['connection', 'play'] },
  { text: 'Have you ever locked eyes with one audience member and performed to them all night?', category: 'the one face', emoji: '👁️', themes: ['connection', 'memory'] },
  { text: 'Kids in the audience: joy or chaos?', category: 'kids in the house', emoji: '🧒', themes: ['play', 'humour'] },
  { text: 'What do you hope people are saying on the drive home?', category: 'the drive home', emoji: '🚗', themes: ['ambition', 'values'] },
  { text: 'What is the difference between an audience watching you and an audience with you?', category: 'with, not at', emoji: '🤝', themes: ['connection', 'craft'] },
  { text: 'What kind of audience member were you before you were a performer?', category: 'audience self', emoji: '🎟️', themes: ['memory', 'identity'] },
  { text: 'Would you rather move an audience to tears or to their feet?', category: 'tears or feet', emoji: '😭', themes: ['values', 'ambition'] },
  { text: 'What show did you watch that made you want to do this?', category: 'the spark show', emoji: '✨', themes: ['memory', 'ambition'] },
  { text: 'What do you notice from the stage that the audience thinks is invisible?', category: 'we can see you', emoji: '🔦', themes: ['humour', 'craft'] },
  { text: "Front row or back of the house — where do you sit when you're the audience?", category: 'where you sit', emoji: '🪑', themes: ['identity', 'place'] },
  { text: 'What is your favorite thing to overhear in the lobby after a show?', category: 'lobby talk', emoji: '🗣️', themes: ['connection', 'play'] },
  { text: 'A standing ovation every night, or one person changed forever per run?', category: 'ovation or one', emoji: '🌠', themes: ['values', 'ambition'] },
  { text: 'What is the hardest audience you ever won over?', category: 'toughest crowd', emoji: '🧊', themes: ['memory', 'courage'] },
  { text: 'When a joke or a moment dies, what is your recovery move?', category: 'the save', emoji: '🪂', themes: ['craft', 'humour'] },
  { text: 'What would you perform if the audience could not clap?', category: 'no applause', emoji: '🤲', themes: ['craft', 'values'] },
  { text: 'Do you want to see the audience, or do you prefer the lights blind you?', category: 'lights up or down', emoji: '💡', themes: ['identity', 'boundaries'] },
  { text: "Applause, a good review, or a stranger's letter — which one actually lands?", category: 'what lands', emoji: '💌', themes: ['connection', 'identity'] },
  { text: 'How do you take a note you disagree with?', category: 'hard notes', emoji: '📝', themes: ['conflict', 'growth'] },
  { text: 'Would you rather get notes right after the show or the next morning?', category: 'note timing', emoji: '🌅', themes: ['boundaries', 'craft'] },
  { text: 'What is the best note anyone ever gave you?', category: 'best note', emoji: '🏅', themes: ['learning', 'memory'] },
  { text: 'Who is allowed to criticize your work?', category: 'earned critics', emoji: '🎯', themes: ['boundaries', 'values'] },
  { text: 'What compliment about your performing do you never get tired of?', category: 'the compliment', emoji: '💛', themes: ['identity', 'connection'] },
  { text: 'Do you read reviews during a run, or after it closes?', category: 'reviews', emoji: '📰', themes: ['boundaries', 'identity'] },
  { text: 'How do you give a hard note without flattening someone?', category: 'giving notes', emoji: '🪶', themes: ['generosity', 'conflict'] },
  { text: "What do you do with praise you don't believe?", category: 'unbelieved praise', emoji: '🪞', themes: ['identity', 'growth'] },
  { text: 'What is a piece of feedback that changed how you perform?', category: 'feedback that stuck', emoji: '🔧', themes: ['learning', 'growth'] },
  { text: 'When the show goes badly, who do you call?', category: 'after a bad one', emoji: '📞', themes: ['connection', 'comfort'] },
  { text: 'What is your honest relationship with applause?', category: 'applause', emoji: '👏', themes: ['identity', 'values'] },
  { text: 'Whose opinion of your work do you secretly perform for?', category: 'the invisible judge', emoji: '👤', themes: ['identity', 'connection'] },
  { text: 'What is the kindest way anyone has ever told you the truth about your work?', category: 'kind truth', emoji: '🤍', themes: ['connection', 'learning'] },
  { text: 'Are you a rehearsal person or a performance person?', category: 'rehearsal or show', emoji: '🎬', themes: ['identity', 'craft'] },
  { text: 'What do you only discover about a piece in front of an audience?', category: 'audience lessons', emoji: '🔍', themes: ['learning', 'craft'] },
  { text: 'How set is your act — locked to the count, or alive every night?', category: 'locked or loose', emoji: '🎲', themes: ['craft', 'identity'] },
  { text: 'What is your favorite kind of rehearsal — first read, messy middle, or final polish?', category: 'rehearsal season', emoji: '🧵', themes: ['craft', 'play'] },
  { text: 'Marking it or going full out — what is your default in rehearsal?', category: 'full out', emoji: '💥', themes: ['craft', 'identity'] },
  { text: 'What do you rehearse that nobody would think to rehearse?', category: 'secret rehearsal', emoji: '🕵️', themes: ['craft', 'ritual'] },
  { text: 'When do you know a piece is ready?', category: 'ready', emoji: '✅', themes: ['craft', 'values'] },
  { text: 'What is a habit from training that you have never dropped?', category: 'training habits', emoji: '🏋️', themes: ['ritual', 'craft'] },
  { text: 'Do your best ideas come in the studio or on stage?', category: 'where ideas live', emoji: '💡', themes: ['creativity', 'craft'] },
  { text: 'What is the most useful mistake you ever made in rehearsal?', category: 'useful mistakes', emoji: '🩹', themes: ['learning', 'growth'] },
  { text: 'How do you keep show one hundred as alive as show one?', category: 'long runs', emoji: '🔁', themes: ['craft', 'growth'] },
  { text: 'What do you love about an empty theater?', category: 'empty theater', emoji: '🏛️', themes: ['place', 'rest'] },
  { text: 'Would you rather have double the rehearsal time or double the run?', category: 'time or run', emoji: '⏳', themes: ['craft', 'ambition'] },
  { text: "Improvise your way out, or drill until it can't go wrong — which one is your instinct?", category: 'improv or drill', emoji: '🧠', themes: ['identity', 'craft'] },
  { text: 'What has to be true before you let someone catch you?', category: 'the catch', emoji: '🤲', themes: ['connection', 'courage'] },
  { text: 'Who checks your rigging, and how did they earn that?', category: 'who checks', emoji: '🪢', themes: ['values', 'connection'] },
  { text: 'What is your relationship with fear when the trick is high?', category: 'working high', emoji: '🎪', themes: ['courage', 'identity'] },
  { text: 'How do you rebuild trust with a partner after a drop?', category: 'after the drop', emoji: '🧩', themes: ['conflict', 'connection'] },
  { text: 'What do you double-check even when someone else already has?', category: 'double check', emoji: '🔍', themes: ['ritual', 'boundaries'] },
  { text: "Would you rather work with someone brilliant you can't rely on, or someone reliable and still learning?", category: 'brilliant or steady', emoji: '⚖️', themes: ['values', 'community'] },
  { text: 'What is a risk you take on stage that the audience never notices?', category: 'invisible risk', emoji: '🫥', themes: ['courage', 'craft'] },
  { text: 'What is a risk you will not take, no matter the applause?', category: 'the hard line', emoji: '🛑', themes: ['boundaries', 'values'] },
  { text: 'How do you tell a partner you are not okay to go tonight?', category: 'calling it', emoji: '🗣️', themes: ['boundaries', 'courage'] },
  { text: 'What makes you trust a new crew member fast?', category: 'fast trust', emoji: '⚡', themes: ['connection', 'community'] },
  { text: 'What is the bravest thing you have seen someone do backstage, not on stage?', category: 'backstage brave', emoji: '🦁', themes: ['courage', 'community'] },
  { text: 'When your gut says something is off with a rig or a trick, how loud is it — and do you listen?', category: 'gut check', emoji: '🧭', themes: ['identity', 'courage'] },
  { text: 'Would you rather be the one flying or the one catching?', category: 'fly or catch', emoji: '🕊️', themes: ['identity', 'connection'] },
  { text: 'What is a safety rule you treat as sacred?', category: 'sacred rules', emoji: '📜', themes: ['values', 'ritual'] },
  { text: 'What did your scariest near-miss teach you?', category: 'near miss', emoji: '⚠️', themes: ['memory', 'learning'] },
  { text: 'What do you owe a partner beyond hitting your cues?', category: 'beyond cues', emoji: '🤝', themes: ['values', 'connection'] },
  { text: 'What kind of leader do you become at ten minutes to doors?', category: 'crunch leader', emoji: '⏱️', themes: ['identity', 'work'] },
  { text: 'Would you rather run the show or steal it?', category: 'run or steal', emoji: '👑', themes: ['ambition', 'identity'] },
  { text: 'What is the first thing you fix when a show is in trouble — the people, the money, or the piece?', category: 'triage', emoji: '🚑', themes: ['work', 'values'] },
  { text: 'How do you get a tired crew through load-out?', category: 'load-out', emoji: '📦', themes: ['community', 'generosity'] },
  { text: 'What did the best director or coach you ever had do differently?', category: 'best director', emoji: '🌟', themes: ['learning', 'memory'] },
  { text: 'What did the worst one teach you?', category: 'worst director', emoji: '🌩️', themes: ['learning', 'conflict'] },
  { text: 'Praise in public, correct in private — do you actually live by it?', category: 'praise and correction', emoji: '📣', themes: ['values', 'conflict'] },
  { text: 'What would your crew say it is like to work for you?', category: 'their version', emoji: '🪞', themes: ['identity', 'community'] },
  { text: 'Do you cast for talent or for the room?', category: 'casting', emoji: '🎭', themes: ['values', 'community'] },
  { text: 'What is a decision only you can make, and what do you always hand off?', category: 'yours to carry', emoji: '🎒', themes: ['work', 'boundaries'] },
  { text: "How do you say no to a performer's idea without dimming them?", category: 'the gentle no', emoji: '🕯️', themes: ['conflict', 'generosity'] },
  { text: 'When do you let a mistake go, and when do you stop the room?', category: 'stop the room', emoji: '✋', themes: ['conflict', 'craft'] },
  { text: 'Would you rather your crew respect you or adore you, if you had to pick?', category: 'respect or adore', emoji: '⚖️', themes: ['values', 'identity'] },
  { text: 'What is your first move when two performers are feuding?', category: 'the feud', emoji: '🕊️', themes: ['conflict', 'community'] },
  { text: 'What does a company need from its leader the morning after a flop?', category: 'after a flop', emoji: '🌧️', themes: ['community', 'courage'] },
  { text: 'Who taught you how to run a room?', category: 'room teachers', emoji: '🧑‍🏫', themes: ['memory', 'learning'] },
  { text: 'What do you never ask of your crew that other leaders do?', category: 'never ask', emoji: '🚫', themes: ['values', 'boundaries'] },
  { text: 'What turns somebody in charge into somebody worth following?', category: 'worth following', emoji: '⚓', themes: ['values', 'community'] },
  { text: 'How do you spot burnout in a performer before they say it?', category: 'spotting burnout', emoji: '🔋', themes: ['community', 'rest'] },
  { text: 'What is a hill you would die on about how a company should be run?', category: 'company hill', emoji: '⛰️', themes: ['values', 'conflict'] },
  { text: "Delegating the thing you love or the thing you're best at — which is harder?", category: 'letting go', emoji: '🎈', themes: ['growth', 'work'] },
  { text: 'What is your dream team size — a duo, a small company, or a cast of dozens?', category: 'company size', emoji: '👥', themes: ['community', 'ambition'] },
  { text: 'What does your costume have to let you do?', category: 'costume function', emoji: '🤸', themes: ['craft', 'identity'] },
  { text: 'Sequins, leather, silk, or bare simplicity — what is your stage material?', category: 'stage material', emoji: '✨', themes: ['identity', 'creativity'] },
  { text: "What is the first thing you notice about another performer's look?", category: 'first look', emoji: '👀', themes: ['craft', 'values'] },
  { text: 'What color owns your stage wardrobe?', category: 'stage color', emoji: '🎨', themes: ['identity', 'creativity'] },
  { text: 'Is your stage makeup armor, mask, or magnification?', category: 'the face', emoji: '💄', themes: ['identity', 'ritual'] },
  { text: 'What is a costume you still think about?', category: 'unforgettable costume', emoji: '🪡', themes: ['memory', 'creativity'] },
  { text: 'Would you rather design the costume yourself or have it built for you exactly right?', category: 'design or wear', emoji: '✂️', themes: ['creativity', 'craft'] },
  { text: 'What everyday clothing rule does your stage self break?', category: 'stage rules', emoji: '👗', themes: ['identity', 'play'] },
  { text: 'What is your aesthetic in three words?', category: 'three words', emoji: '🏷️', themes: ['identity', 'creativity'] },
  { text: 'How much of your offstage wardrobe leaks into your costumes — or the other way around?', category: 'the leak', emoji: '🌀', themes: ['identity', 'home'] },
  { text: 'What look have you retired that deserves a moment of silence?', category: 'retired look', emoji: '🪦', themes: ['memory', 'humour'] },
  { text: 'Glitter: yes, no, or it gets everywhere but yes?', category: 'glitter', emoji: '✨', themes: ['humour', 'play'] },
  { text: 'What matters more in a costume: how it looks at ten feet, or how it feels at full extension?', category: 'ten feet or full extension', emoji: '📏', themes: ['craft', 'values'] },
  { text: 'What is a beautiful thing on stage that the audience never sees up close?', category: 'hidden beauty', emoji: '🔬', themes: ['craft', 'creativity'] },
  { text: 'Who dresses better: your stage self or your street self?', category: 'two wardrobes', emoji: '🧥', themes: ['identity', 'humour'] },
  { text: 'What is the most repaired item in your costume bag?', category: 'the survivor', emoji: '🧵', themes: ['craft', 'memory'] },
  { text: 'What color of light makes you feel most like yourself up there?', category: 'your light', emoji: '💡', themes: ['identity', 'place'] },
  { text: 'If your act had a signature scent, what would it be?', category: 'signature scent', emoji: '🌸', themes: ['creativity', 'play'] },
  { text: 'What is the smallest costume detail you refuse to skip?', category: 'small details', emoji: '📍', themes: ['craft', 'ritual'] },
  { text: 'Would you rather look mysterious, dazzling, dangerous, or warm on stage?', category: 'stage aura', emoji: '🔮', themes: ['identity', 'creativity'] },
  { text: 'What part of the business side do you secretly enjoy?', category: 'secret business joy', emoji: '📊', themes: ['work', 'play'] },
  { text: 'What would you pay someone else to do tomorrow: booking, budgets, or marketing?', category: 'first hire', emoji: '💼', themes: ['work', 'boundaries'] },
  { text: 'How do you price your work without flinching?', category: 'naming the price', emoji: '💰', themes: ['courage', 'values'] },
  { text: 'What is a gig you turned down that you are proud of?', category: 'the good no', emoji: '🚪', themes: ['boundaries', 'values'] },
  { text: 'What is a gig you took for the money that gave you more than money?', category: 'surprise gig', emoji: '🎁', themes: ['memory', 'work'] },
  { text: 'Free tickets for friends: generous tradition or slippery slope?', category: 'comps', emoji: '🎟️', themes: ['generosity', 'boundaries'] },
  { text: 'What makes a venue worth working with twice?', category: 'good venues', emoji: '🏛️', themes: ['values', 'work'] },
  { text: 'What is the most useful thing you know about contracts that nobody taught you?', category: 'contract wisdom', emoji: '📄', themes: ['learning', 'work'] },
  { text: 'Would you rather sell out a small room or half-fill a big one?', category: 'room math', emoji: '🧮', themes: ['values', 'ambition'] },
  { text: 'How do you know when it is time to close a show?', category: 'closing time', emoji: '🌙', themes: ['values', 'courage'] },
  { text: "What would you spend a surprise five thousand on: the rig, costumes, marketing, or the crew's pay?", category: 'found money', emoji: '💸', themes: ['values', 'work'] },
  { text: 'How does your audience actually find you?', category: 'how they find you', emoji: '🔎', themes: ['community', 'work'] },
  { text: 'Who is the connector in your corner of the industry — the one who somehow knows everyone?', category: 'the connector', emoji: '🕸️', themes: ['community', 'connection'] },
  { text: 'What is your relationship with self-promotion?', category: 'the plug', emoji: '📣', themes: ['identity', 'courage'] },
  { text: 'What show business rule do you think is nonsense?', category: 'show biz nonsense', emoji: '🧨', themes: ['values', 'boundaries'] },
  { text: 'What do you wish audiences understood about what a ticket pays for?', category: 'ticket truth', emoji: '🎫', themes: ['values', 'work'] },
  { text: 'Would you rather have a great agent or a great accountant?', category: 'agent or accountant', emoji: '🧾', themes: ['work', 'humour'] },
  { text: 'What is the first thing you check after opening night: sales, reviews, or your own gut?', category: 'the morning after', emoji: '☀️', themes: ['identity', 'work'] },
  { text: 'What is a marketing move you tried that actually worked?', category: 'what worked', emoji: '📈', themes: ['work', 'learning'] },
  { text: 'A day job plus the art, or all art all the time — what is your honest ideal?', category: 'the split', emoji: '⚖️', themes: ['work', 'values'] },
  { text: 'Spotlight or backstage: where is your natural home?', category: 'your side of the curtain', emoji: '🎪', themes: ['identity', 'place'] },
  { text: 'What backstage job would you do forever if you never performed again?', category: 'backstage forever', emoji: '🔧', themes: ['identity', 'work'] },
  { text: 'Who is the most important person in a theater that the audience never sees?', category: 'unseen essential', emoji: '🖤', themes: ['values', 'community'] },
  { text: "What do you love about the wings that the stage can't give you?", category: 'the wings', emoji: '🌑', themes: ['place', 'identity'] },
  { text: 'Would you rather call the show from the booth or hold the spotlight?', category: 'booth or beam', emoji: '🎚️', themes: ['identity', 'work'] },
  { text: 'What is a stagehand skill you wish you had?', category: 'crew envy', emoji: '🛠️', themes: ['learning', 'craft'] },
  { text: 'How do you thank the crew in a way that actually counts?', category: 'thanking the crew', emoji: '🙏', themes: ['generosity', 'community'] },
  { text: 'When the light hits you, what changes?', category: 'in the beam', emoji: '💡', themes: ['identity', 'courage'] },
  { text: 'What is your favorite backstage sound?', category: 'backstage sounds', emoji: '🔊', themes: ['place', 'comfort'] },
  { text: 'Are you different in the greenroom than in the lobby?', category: 'two rooms', emoji: '🚪', themes: ['identity', 'community'] },
  { text: 'What would your dressing room mirror say about you?', category: 'mirror report', emoji: '🪞', themes: ['identity', 'humour'] },
  { text: 'What is satisfying about making magic nobody knows you made?', category: 'invisible magic', emoji: '🎩', themes: ['craft', 'values'] },
  { text: "A show caller's calm or a performer's fire — which one do you run on?", category: 'calm or fire', emoji: '🔥', themes: ['identity', 'work'] },
  { text: "What is your favorite tech week memory, now that it's over?", category: 'tech week', emoji: '🌙', themes: ['memory', 'humour'] },
  { text: 'What does your body ask for after a two-show day?', category: 'two-show day', emoji: '🛁', themes: ['rest', 'comfort'] },
  { text: 'What is your non-negotiable recovery ritual?', category: 'recovery ritual', emoji: '🧊', themes: ['rest', 'ritual'] },
  { text: 'What do you change on the days your body is tired but the show is on?', category: 'tired but on', emoji: '🔋', themes: ['craft', 'rest'] },
  { text: 'What injury taught you the most?', category: 'the teacher injury', emoji: '🩹', themes: ['learning', 'growth'] },
  { text: 'What is your relationship with rest days: sacred, guilty, or forgotten?', category: 'rest days', emoji: '🛌', themes: ['rest', 'boundaries'] },
  { text: "What does warm actually feel like in your body, the moment you know you're ready?", category: 'ready warmth', emoji: '♨️', themes: ['craft', 'ritual'] },
  { text: 'Sleep, food, or stretching — which one do you guard hardest during a run?', category: 'the guard', emoji: '🛡️', themes: ['rest', 'boundaries'] },
  { text: 'What is the oldest ache you perform with?', category: 'old ache', emoji: '🦴', themes: ['identity', 'memory'] },
  { text: 'What do your hands say about your work?', category: 'hands', emoji: '✋', themes: ['craft', 'identity'] },
  { text: 'How will you know when it is time to change what you perform?', category: 'the pivot', emoji: '🧭', themes: ['growth', 'courage'] },
  { text: 'What is a stretch, exercise, or drill you actually enjoy?', category: 'the good drill', emoji: '🤸', themes: ['play', 'craft'] },
  { text: 'What do you eat in the twenty minutes between shows?', category: 'between shows', emoji: '🥨', themes: ['food', 'ritual'] },
  { text: 'A bath, the couch, a walk, or people — what fixes you after closing night?', category: 'closing repair', emoji: '🛋️', themes: ['rest', 'comfort'] },
  { text: 'What is something your body can do that still surprises you?', category: 'body surprise', emoji: '⚡', themes: ['identity', 'play'] },
  { text: 'What was your first time on any stage?', category: 'first stage', emoji: '🌱', themes: ['memory', 'courage'] },
  { text: 'What smell means theater to you?', category: 'theater smell', emoji: '👃', themes: ['memory', 'place'] },
  { text: "What is the first act you ever saw that you couldn't explain?", category: 'unexplainable act', emoji: '🪄', themes: ['memory', 'creativity'] },
  { text: 'Who put you on stage first, and did they know what they started?', category: 'the instigator', emoji: '🔥', themes: ['memory', 'family'] },
  { text: "What is a performance you gave that nobody photographed, but you'll never forget?", category: 'unphotographed', emoji: '📷', themes: ['memory', 'craft'] },
  { text: 'What costume from childhood explains your whole career?', category: 'childhood costume', emoji: '🧒', themes: ['memory', 'humour'] },
  { text: "What is a mark or callus you earned that you're weirdly proud of?", category: 'earned marks', emoji: '💪', themes: ['identity', 'memory'] },
  { text: 'What was the first skill that made you feel like a performer?', category: 'first skill', emoji: '🎯', themes: ['memory', 'craft'] },
  { text: 'What show would you re-watch from the wings if you could time travel?', category: 'time travel ticket', emoji: '⏳', themes: ['memory', 'place'] },
  { text: 'What is a piece of your training you resented then and treasure now?', category: 'resented then', emoji: '🏺', themes: ['memory', 'growth'] },
  { text: 'What was your best worst gig?', category: 'best worst gig', emoji: '🎢', themes: ['memory', 'humour'] },
  { text: 'Who from your performing past do you wish could see you now?', category: 'wish they could see', emoji: '🌠', themes: ['memory', 'connection'] },
  { text: 'What is the first applause you actually remember?', category: 'first applause', emoji: '👏', themes: ['memory', 'identity'] },
  { text: 'What is a venue that no longer exists that you still miss?', category: 'gone venues', emoji: '🕯️', themes: ['place', 'memory'] },
  { text: 'What is the oldest thing in your kit, and why is it still there?', category: 'oldest kit', emoji: '🎒', themes: ['memory', 'ritual'] },
  { text: 'What did your younger performer self worry about that turned out fine?', category: 'young worries', emoji: '🫧', themes: ['memory', 'growth'] },
  { text: 'What does your home have that a dressing room never could?', category: 'home vs dressing room', emoji: '🏠', themes: ['home', 'comfort'] },
  { text: 'Where does your gear live at home, honestly?', category: 'gear at home', emoji: '🧳', themes: ['home', 'humour'] },
  { text: 'What do your neighbors think is going on when you train at home?', category: 'the neighbors', emoji: '🏘️', themes: ['humour', 'home'] },
  { text: 'What is your offstage uniform?', category: 'offstage uniform', emoji: '🧢', themes: ['identity', 'comfort'] },
  { text: 'How do you come down after a show — fast, slow, or not until 3am?', category: 'the comedown', emoji: '🌃', themes: ['rest', 'ritual'] },
  { text: 'What does an ideal dark day look like?', category: 'dark day', emoji: '🌑', themes: ['rest', 'play'] },
  { text: 'Who at home keeps you sane during a run?', category: 'home crew', emoji: '🤍', themes: ['family', 'connection'] },
  { text: 'What is a domestic skill your show life gave you?', category: 'transferable', emoji: '🧰', themes: ['home', 'craft'] },
  { text: 'What is on your walls: show posters, or anything but?', category: 'the walls', emoji: '🖼️', themes: ['home', 'identity'] },
  { text: 'How do you explain your job at a family dinner?', category: 'family dinner', emoji: '🍽️', themes: ['family', 'humour'] },
  { text: 'What do you cook when the tour finally ends?', category: 'home cooking', emoji: '🍲', themes: ['food', 'home'] },
  { text: 'Where in your home does the performer in you fully switch off?', category: 'off switch', emoji: '🛋️', themes: ['home', 'rest'] },
  { text: 'What is your first move in a new city on tour?', category: 'new city', emoji: '🗺️', themes: ['place', 'ritual'] },
  { text: 'What do you pack that nobody else would think to?', category: 'the odd pack', emoji: '🧳', themes: ['ritual', 'humour'] },
  { text: 'What is the best stage door you have ever walked through?', category: 'stage doors', emoji: '🚪', themes: ['place', 'memory'] },
  { text: 'Would you rather tour forever or have one home venue forever?', category: 'road or residency', emoji: '🛣️', themes: ['place', 'ambition'] },
  { text: 'What makes a green room actually good?', category: 'green room standards', emoji: '🛋️', themes: ['place', 'comfort'] },
  { text: 'What is your favorite kind of venue: black box, big top, ballroom, or street corner?', category: 'venue love', emoji: '🎪', themes: ['place', 'identity'] },
  { text: 'What city surprised you with its audience?', category: 'surprise city', emoji: '🌆', themes: ['place', 'memory'] },
  { text: 'What is your tour van personality?', category: 'travel self', emoji: '🚌', themes: ['identity', 'humour'] },
  { text: 'What do you find first in a new town: the gym, the coffee, the laundromat, or the diner?', category: 'town anchors', emoji: '📍', themes: ['place', 'ritual'] },
  { text: 'What is the strangest place you have ever performed?', category: 'strangest stage', emoji: '🌵', themes: ['memory', 'place'] },
  { text: 'How do you make a hotel room feel like yours in ten minutes?', category: 'hotel nesting', emoji: '🛏️', themes: ['home', 'ritual'] },
  { text: 'What is a stage you dream of standing on?', category: 'dream stage', emoji: '🌠', themes: ['ambition', 'place'] },
  { text: 'What is better about shows in a tiny town than in a big city?', category: 'small town shows', emoji: '🌾', themes: ['place', 'community'] },
  { text: 'What do you miss most from home by week three of a tour?', category: 'week three', emoji: '📆', themes: ['home', 'family'] },
  { text: 'If you opened your own show next year, what is its name?', category: 'name the show', emoji: '🏷️', themes: ['ambition', 'creativity'] },
  { text: 'What would your show refuse to compromise on?', category: 'the uncompromised', emoji: '💎', themes: ['values', 'ambition'] },
  { text: 'Whose career would you happily borrow the shape of?', category: 'career shapes', emoji: '📐', themes: ['ambition', 'learning'] },
  { text: "What scares you more: starting your own thing, or staying in someone else's?", category: 'the scarier thing', emoji: '🎢', themes: ['courage', 'ambition'] },
  { text: 'What is the act you have not built yet that keeps knocking?', category: 'the knocking act', emoji: '🚪', themes: ['creativity', 'ambition'] },
  { text: 'Would you rather be a legend in one discipline or beloved across many?', category: 'deep or wide', emoji: '🌊', themes: ['ambition', 'identity'] },
  { text: 'What does "making it" look like for you, specifically?', category: 'making it', emoji: '🎯', themes: ['ambition', 'values'] },
  { text: 'What would you do in this industry if money were boring and solved?', category: 'money solved', emoji: '🪙', themes: ['ambition', 'play'] },
  { text: 'Five years from now, are you performing, directing, producing, or teaching?', category: 'five years', emoji: '🔭', themes: ['ambition', 'growth'] },
  { text: "What skill outside performing would you master to serve the dream?", category: 'the side skill', emoji: '🧮', themes: ['learning', 'ambition'] },
  { text: 'Who would you call first if you got the big yes tomorrow?', category: 'the big yes', emoji: '📞', themes: ['connection', 'ambition'] },
  { text: "What is your show's opening image — the first thing the audience sees?", category: 'opening image', emoji: '🌅', themes: ['creativity', 'ambition'] },
  { text: 'What is a dream collaboration that would make you nervous to ask for?', category: 'nervous ask', emoji: '💌', themes: ['courage', 'connection'] },
  { text: 'What would you want written on the poster besides your name?', category: 'the poster', emoji: '🪧', themes: ['ambition', 'identity'] },
  { text: "What tradition from shows you've worked on would you carry into your own company?", category: 'carried traditions', emoji: '🧬', themes: ['ritual', 'community'] },
  { text: 'What tradition would you leave behind?', category: 'left behind', emoji: '🍂', themes: ['values', 'growth'] },
  { text: 'Would you rather premiere at a festival, in a theater, or somewhere no show has ever been?', category: 'the premiere', emoji: '🎉', themes: ['ambition', 'place'] },
  { text: "What do you want your show to leave in people's bodies, not just their heads?", category: 'in the body', emoji: '🫀', themes: ['creativity', 'values'] },
  { text: 'What is your stage name story — real name, chosen name, or secret third thing?', category: 'the name', emoji: '🏷️', themes: ['identity', 'memory'] },
  { text: 'How far apart are stage-you and kitchen-table-you?', category: 'the gap', emoji: '🌗', themes: ['identity', 'home'] },
  { text: 'What can stage-you do that everyday-you is still learning?', category: 'stage powers', emoji: '⚡', themes: ['identity', 'growth'] },
  { text: 'What does everyday-you know that stage-you forgets?', category: 'everyday wisdom', emoji: '🌱', themes: ['identity', 'growth'] },
  { text: 'Are you a different performer at 2pm than at 10pm?', category: 'matinee self', emoji: '🕑', themes: ['identity', 'humour'] },
  { text: 'What is a persona you tried on and returned?', category: 'returned persona', emoji: '🧥', themes: ['identity', 'memory'] },
  { text: 'What part of your act is the most honest thing about you?', category: 'the honest part', emoji: '💎', themes: ['identity', 'values'] },
  { text: 'If your act were an animal, which one and why?', category: 'act animal', emoji: '🦚', themes: ['identity', 'play'] },
  { text: 'What music would play when you enter, if life had entrances?', category: 'entrance music', emoji: '🎺', themes: ['identity', 'play'] },
  { text: 'What do people get wrong about performers like you?', category: 'the myth', emoji: '🫧', themes: ['identity', 'values'] },
  { text: 'Villain, ingenue, clown, or mystery — which stage type keeps choosing you?', category: 'typecast', emoji: '🎭', themes: ['identity', 'humour'] },
  { text: 'Can you stand to watch recordings of yourself?', category: 'watching yourself', emoji: '📹', themes: ['identity', 'courage'] },
  { text: "What is your body's signature move, the one that is just yours?", category: 'signature move', emoji: '🌀', themes: ['identity', 'craft'] },
  { text: 'What is a compliment about your presence, not your skill, that stuck?', category: 'presence praise', emoji: '✨', themes: ['identity', 'connection'] },
  { text: 'When did you last surprise yourself on stage?', category: 'self surprise', emoji: '🎇', themes: ['identity', 'memory'] },
  { text: 'What would you perform under a pseudonym that you would never perform under your name?', category: 'the pseudonym', emoji: '🎭', themes: ['identity', 'courage'] },
  { text: 'Where do new acts start for you: music first, image first, or trick first?', category: 'the seed', emoji: '🌱', themes: ['creativity', 'craft'] },
  { text: 'What is in your ideas notebook right now — real answer?', category: 'the notebook', emoji: '📓', themes: ['creativity', 'ambition'] },
  { text: 'What piece of music are you saving for the right act?', category: 'saved music', emoji: '🎼', themes: ['creativity', 'ritual'] },
  { text: 'How do you know when an idea is yours to make, and when it is only yours to admire?', category: 'yours to make', emoji: '🪞', themes: ['creativity', 'identity'] },
  { text: 'What do you steal like an artist, and from where?', category: 'good theft', emoji: '🖼️', themes: ['creativity', 'learning'] },
  { text: 'What is your relationship with deadlines: enemy, engine, or excuse?', category: 'deadlines', emoji: '⏰', themes: ['work', 'creativity'] },
  { text: 'What is the weirdest source that ever became an act?', category: 'weird sources', emoji: '🧪', themes: ['creativity', 'humour'] },
  { text: 'Do you make for the audience you have, or the audience you want?', category: "who it's for", emoji: '🎯', themes: ['creativity', 'values'] },
  { text: 'What would you make if nobody ever saw it?', category: 'unseen making', emoji: '🌒', themes: ['creativity', 'identity'] },
  { text: 'What is a prop you have always wanted to build an act around?', category: 'the prop', emoji: '🪑', themes: ['creativity', 'play'] },
  { text: 'When you are creatively empty, what refills you?', category: 'the refill', emoji: '⛲', themes: ['creativity', 'rest'] },
  { text: 'What kind of act does the world have quite enough of already?', category: 'enough already', emoji: '🙅', themes: ['humour', 'values'] },
  { text: 'What discipline outside yours do you raid for ideas?', category: 'raiding disciplines', emoji: '🏴‍☠️', themes: ['creativity', 'learning'] },
  { text: 'Do you choreograph on paper, in your body, or in your sleep?', category: 'where you choreograph', emoji: '💭', themes: ['creativity', 'craft'] },
  { text: "What is a beautiful idea you had to cut because it didn't serve the show?", category: 'the darling', emoji: '🥀', themes: ['creativity', 'values'] },
  { text: 'What act would you make about your own life right now?', category: 'life as act', emoji: '📖', themes: ['creativity', 'identity'] },
  { text: 'What turns a cast into a company?', category: 'company feeling', emoji: '🐝', themes: ['community', 'values'] },
  { text: 'What is your role in the greenroom ecosystem?', category: 'greenroom role', emoji: '🛋️', themes: ['community', 'identity'] },
  { text: 'What is a company tradition you would defend fiercely?', category: 'defended traditions', emoji: '🛡️', themes: ['ritual', 'community'] },
  { text: 'How do you welcome a new cast member on day one?', category: 'day one', emoji: '👋', themes: ['community', 'generosity'] },
  { text: 'What is the fastest a group of strangers ever became your people?', category: 'fast family', emoji: '⚡', themes: ['community', 'memory'] },
  { text: 'What do you contribute to a company that never appears in the program?', category: 'off-program', emoji: '📄', themes: ['generosity', 'community'] },
  { text: 'Cast dinners: who are you at the table?', category: 'cast dinner', emoji: '🍝', themes: ['community', 'food'] },
  { text: 'What is the kindest thing a castmate ever did for you mid-show?', category: 'mid-show kindness', emoji: '🤲', themes: ['generosity', 'memory'] },
  { text: 'What keeps a company together when the run gets hard?', category: 'the glue', emoji: '🧲', themes: ['community', 'values'] },
  { text: 'What is a conflict in a cast you have seen repaired beautifully?', category: 'beautiful repair', emoji: '🪡', themes: ['conflict', 'community'] },
  { text: 'Would you rather work with your best friends or with the best in the field?', category: 'friends or masters', emoji: '⚖️', themes: ['community', 'values'] },
  { text: 'Who was your first show family?', category: 'first show family', emoji: '🏡', themes: ['family', 'memory'] },
  { text: "What is something you learned about a castmate that you'd never have learned outside a show?", category: 'show knowledge', emoji: '🔦', themes: ['connection', 'community'] },
  { text: "What do you do when a company's culture starts going sour?", category: 'sour culture', emoji: '🍋', themes: ['conflict', 'community'] },
  { text: 'What is your green flag in a company on day one?', category: 'company green flags', emoji: '💚', themes: ['community', 'values'] },
  { text: 'How do you keep in touch with show families after closing?', category: 'after closing', emoji: '💌', themes: ['connection', 'ritual'] },
  { text: 'Who would you take a beginner class from tomorrow, in anything?', category: 'beginner again', emoji: '🌱', themes: ['learning', 'play'] },
  { text: 'What do you teach best that you were never formally taught?', category: 'untaught teaching', emoji: '🎓', themes: ['generosity', 'learning'] },
  { text: 'What is your favorite thing about coaching someone through a fear?', category: 'coaching fear', emoji: '🪜', themes: ['generosity', 'courage'] },
  { text: 'What discipline would you add to your act if learning were instant?', category: 'instant skill', emoji: '🪄', themes: ['learning', 'ambition'] },
  { text: 'How do you learn choreography: counts, feeling, landmarks, or repetition?', category: 'how you learn', emoji: '🧠', themes: ['learning', 'craft'] },
  { text: 'What is something a student taught you?', category: 'student lessons', emoji: '🔄', themes: ['learning', 'generosity'] },
  { text: 'What is a lesson from another performer you think about weekly?', category: 'weekly lesson', emoji: '📌', themes: ['learning', 'memory'] },
  { text: 'What technique took you embarrassingly long to get, and was worth every day of it?', category: 'the long get', emoji: '🐢', themes: ['learning', 'growth'] },
  { text: 'What do you wish someone had told you in your first year?', category: 'first year advice', emoji: '💌', themes: ['learning', 'generosity'] },
  { text: 'What do you practice in line at the grocery store?', category: 'grocery practice', emoji: '🛒', themes: ['humour', 'craft'] },
  { text: 'Whose warm-up would you love to shadow for a week?', category: 'shadow week', emoji: '👥', themes: ['learning', 'ritual'] },
  { text: 'What is the best question a student ever asked you?', category: 'student questions', emoji: '❓', themes: ['learning', 'connection'] },
  { text: 'What would you study if you took a season completely off?', category: 'the season off', emoji: '📚', themes: ['learning', 'rest'] },
  { text: 'What is a fundamental you still drill after all these years?', category: 'forever fundamentals', emoji: '🔁', themes: ['craft', 'ritual'] },
  { text: 'On stage, do you trust the plan or the moment?', category: 'plan or moment', emoji: '🎲', themes: ['identity', 'craft'] },
  { text: 'What decision do you make instantly that others agonize over?', category: 'instant call', emoji: '⚡', themes: ['identity', 'work'] },
  { text: 'What decision do you agonize over that others make instantly?', category: 'the agonizer', emoji: '🐌', themes: ['identity', 'humour'] },
  { text: 'When did your gut save a show?', category: 'gut save', emoji: '🦸', themes: ['memory', 'courage'] },
  { text: 'When did your gut get it completely wrong?', category: 'gut fail', emoji: '🙈', themes: ['memory', 'humour'] },
  { text: 'Do you decide better at the last minute, or with a week to sit?', category: 'decision timing', emoji: '⏳', themes: ['identity', 'work'] },
  { text: 'What do you sleep on, always, no matter how sure you feel?', category: 'sleep on it', emoji: '🛌', themes: ['values', 'work'] },
  { text: 'Cut the act or fight for it: how do you decide when time runs short?', category: 'the cut', emoji: '✂️', themes: ['conflict', 'craft'] },
  { text: 'What is a snap judgment about people you have learned to distrust?', category: 'snap judgments', emoji: '🫢', themes: ['growth', 'connection'] },
  { text: 'What is a snap judgment of yours that is almost always right?', category: 'trusted instinct', emoji: '🎯', themes: ['identity', 'connection'] },
  { text: 'In an onstage emergency, are you ice or fire?', category: 'ice or fire', emoji: '🧊', themes: ['identity', 'courage'] },
  { text: 'What choice in your career looked reckless and was actually calculated?', category: 'calculated reckless', emoji: '🧮', themes: ['courage', 'memory'] },
  { text: "What is your best onstage disaster story, now that it's funny?", category: 'disaster story', emoji: '🤡', themes: ['humour', 'memory'] },
  { text: 'What prop has personally betrayed you?', category: 'prop betrayal', emoji: '🎪', themes: ['humour', 'memory'] },
  { text: 'What is the hardest you have ever tried not to laugh on stage?', category: 'corpsing', emoji: '😆', themes: ['humour', 'memory'] },
  { text: 'What backstage prank tradition do you endorse?', category: 'pranks', emoji: '🃏', themes: ['play', 'community'] },
  { text: 'What would the blooper reel of your career open with?', category: 'blooper reel', emoji: '🎬', themes: ['humour', 'memory'] },
  { text: 'What is a completely unserious act you would love to perform just once?', category: 'unserious act', emoji: '🪿', themes: ['play', 'creativity'] },
  { text: 'What is your most dramatic offstage entrance to something mundane?', category: 'mundane drama', emoji: '🛒', themes: ['humour', 'play'] },
  { text: 'What do you do with dead time backstage during a long cue?', category: 'dead time', emoji: '🕰️', themes: ['play', 'ritual'] },
  { text: 'Which castmate archetype are you: the snack bringer, the medic, the DJ, or the group chat?', category: 'cast archetype', emoji: '🧃', themes: ['community', 'humour'] },
  { text: 'What is the funniest thing an audience member has ever done?', category: 'audience antics', emoji: '🍿', themes: ['humour', 'memory'] },
  { text: 'What is a heckle you actually respected?', category: 'respected heckle', emoji: '🎤', themes: ['humour', 'courage'] },
  { text: 'What ridiculous thing lives in your gig bag right now?', category: 'gig bag secrets', emoji: '👜', themes: ['humour', 'ritual'] },
  { text: 'What is the worst costume malfunction you survived — with dignity or without?', category: 'malfunction', emoji: '🧷', themes: ['humour', 'memory'] },
  { text: 'If your career were a sideshow banner, what would it promise?', category: 'the banner', emoji: '🎪', themes: ['humour', 'identity'] },
  { text: 'What award should exist at every cast party?', category: 'cast party awards', emoji: '🏆', themes: ['humour', 'community'] },
  { text: 'What warm-up game do you secretly love?', category: 'warm-up games', emoji: '🎲', themes: ['play', 'ritual'] },
  { text: 'Why live performance, when film pays better and lasts forever?', category: 'why live', emoji: '🕯️', themes: ['values', 'identity'] },
  { text: 'What would make you walk away from a production mid-run?', category: 'the walk-away', emoji: '🚶', themes: ['values', 'boundaries'] },
  { text: 'What do you owe an audience, at minimum, every single night?', category: 'the minimum owed', emoji: '🎟️', themes: ['values', 'craft'] },
  { text: 'What does this industry get right that outsiders never see?', category: 'industry secrets', emoji: '💛', themes: ['values', 'community'] },
  { text: 'What change would you make to this industry with a magic wand?', category: 'the wand', emoji: '🪄', themes: ['values', 'ambition'] },
  { text: 'What makes a performance count, for you — an audience, a stage, or something else?', category: 'what counts', emoji: '✔️', themes: ['values', 'identity'] },
  { text: 'What tradition in performance do you think is secretly sacred?', category: 'secretly sacred', emoji: '🕊️', themes: ['values', 'ritual'] },
  { text: 'Whose approval in this industry would mean the most, and why them?', category: 'the approval', emoji: '🌟', themes: ['values', 'connection'] },
  { text: 'What line will your art never cross for a laugh or a gasp?', category: 'the line', emoji: '🚧', themes: ['values', 'boundaries'] },
  { text: 'What do you want performance to do for the people watching — escape, mirror, or medicine?', category: "what it's for", emoji: '💊', themes: ['values', 'creativity'] },
  { text: 'When did a show turn out to matter far more than anyone expected?', category: 'when it mattered', emoji: '🌠', themes: ['values', 'memory'] },
  { text: 'What is worth more: a perfect show or an honest one?', category: 'perfect or honest', emoji: '⚖️', themes: ['values', 'craft'] },
  { text: 'What is your closing night ritual?', category: 'closing night', emoji: '🥂', themes: ['ritual', 'community'] },
  { text: 'Do you keep something from every show — a prop, a program, a photo?', category: 'show keepsakes', emoji: '🗃️', themes: ['ritual', 'memory'] },
  { text: 'What is your opening night good luck exchange — cards, gifts, words?', category: 'opening gifts', emoji: '💌', themes: ['ritual', 'generosity'] },
  { text: "How do you mark the last time you'll ever perform a certain act?", category: 'act funerals', emoji: '🕯️', themes: ['ritual', 'memory'] },
  { text: 'What is the first thing you do when you get to any venue?', category: 'venue arrival', emoji: '🚪', themes: ['ritual', 'place'] },
  { text: 'What do you say instead of good luck, and does it matter?', category: 'instead of luck', emoji: '🍀', themes: ['ritual', 'values'] },
  { text: 'What is your intermission routine, minute by minute?', category: 'intermission', emoji: '⏸️', themes: ['ritual', 'rest'] },
  { text: 'How do you celebrate a good show that nobody else noticed was good?', category: 'private wins', emoji: '🥂', themes: ['ritual', 'identity'] },
  { text: 'What is your ghost light — the small thing that keeps the dark friendly?', category: 'ghost light', emoji: '💡', themes: ['ritual', 'comfort'] },
  { text: 'What anniversary from your performing life do you quietly keep?', category: 'kept anniversaries', emoji: '📅', themes: ['ritual', 'memory'] },
  { text: 'What is the correct way to strike a set: solemn, loud, or fast as possible?', category: 'the strike', emoji: '🔨', themes: ['ritual', 'community'] },
  { text: 'What tiny ritual would you add to curtain call if you ran the world?', category: 'curtain call', emoji: '🌹', themes: ['ritual', 'creativity'] },
  { text: 'How do you want to be told you are about to be cut from a number?', category: 'hard news', emoji: '📉', themes: ['conflict', 'boundaries'] },
  { text: 'What is a fight worth having in a rehearsal room?', category: 'worthy fights', emoji: '🥊', themes: ['conflict', 'values'] },
  { text: "How do you apologize when you wrecked someone's cue?", category: 'the apology', emoji: '🤲', themes: ['conflict', 'generosity'] },
  { text: "What do you do when a director's vision and your body disagree?", category: 'vision vs body', emoji: '🧗', themes: ['conflict', 'boundaries'] },
  { text: "What is your tell that you're angry but still being professional?", category: 'professional anger', emoji: '🌋', themes: ['conflict', 'identity'] },
  { text: 'Cold war or clear the air — what is your default in cast tension?', category: 'clearing air', emoji: '🌬️', themes: ['conflict', 'identity'] },
  { text: 'What is a note you refused, and were you right?', category: 'the refused note', emoji: '🙅', themes: ['conflict', 'courage'] },
  { text: 'When is competition between performers healthy, and when does it curdle?', category: 'rivalry', emoji: '🏁', themes: ['conflict', 'community'] },
  { text: 'What did a disagreement about art teach you about a person?', category: 'art fights', emoji: '🎨', themes: ['conflict', 'learning'] },
  { text: 'How long do you carry a bad review, honestly?', category: 'carrying reviews', emoji: '🎒', themes: ['identity', 'boundaries'] },
  { text: 'What is the correct cast party food?', category: 'cast party menu', emoji: '🍕', themes: ['food', 'community'] },
  { text: 'What snack is always in your gig bag?', category: 'gig snack', emoji: '🥜', themes: ['food', 'ritual'] },
  { text: 'What is your post-show meal at 11pm — the real answer?', category: 'the 11pm meal', emoji: '🌮', themes: ['food', 'comfort'] },
  { text: 'What food is banned near your costume, forever?', category: 'costume hazards', emoji: '🍫', themes: ['food', 'humour'] },
  { text: 'Coffee, tea, or something stranger — what fuels your call time?', category: 'call time fuel', emoji: '☕', themes: ['food', 'ritual'] },
  { text: 'What is a dish from a tour stop you still crave?', category: 'tour cravings', emoji: '🍜', themes: ['food', 'place'] },
  { text: 'Who fed you when you were a broke young performer?', category: 'who fed you', emoji: '🍞', themes: ['food', 'generosity'] },
  { text: 'What would you serve at intermission if you ran the concession stand?', category: 'concessions', emoji: '🍿', themes: ['food', 'play'] },
];
