import type { DailyQuestion } from './dailyQuestions';

/**
 * Tech HIVE's own 365 daily questions.
 *
 * Nat's vision (2026-08-12): every HIVE gets its own year of questions,
 * flavored to who they are, so a person in two HIVEs never gets asked the
 * same thing twice. The questions stay innocuous and fun on the surface while
 * quietly revealing how each person thinks, learns, works and decides — a
 * personality test hiding in plain sight. Over a year of answers, Tech HIVE's
 * members find who works LIKE them and who thinks OPPOSITE to them, and both
 * of those are gold: when you are stuck, your opposite is the one you want.
 *
 * The flavor comes from the shelf Nat named (2026-07-31) — Culture Code, Five
 * Dysfunctions of a Team, Never Split the Difference, Thinking Fast and Slow,
 * Code of the Extraordinary Mind, Shoe Dog, Boys in the Boat, How to Win
 * Friends, The 4-Hour Work Week — plus kin like The Tipping Point, Quiet,
 * Range and Drive. These are questions those books would ASK, never questions
 * ABOUT those books.
 *
 * ## Rules for this deck
 *
 * - **Indices 0–31 are frozen.** They are the original 32, live since Tech
 *   HIVE's first day, and members' saved answers point at them by
 *   `question_index`. Never reorder, reword or remove them.
 * - **Append only** after that, for the same reason.
 * - Every question carries 1–3 `themes` from `questionThemes.ts` — that short
 *   shared list is how a Tech answer and an OG answer to completely different
 *   questions can still find each other in the Swarm Report.
 * - Questions 32 onward were drafted 2026-08-12 and are a DRAFT for Nat to
 *   read in the running app.
 */
export const TECH_DAILY_QUESTIONS: DailyQuestion[] = [
  // ── The original 32 — live since Tech HIVE's first day. Frozen. ──
  { text: 'What has to be true for you to trust someone with your unfinished work?', category: 'trust', emoji: '🤝', themes: ['connection', 'courage'] },
  { text: 'When you disagree with the room, do you say it straight away, sleep on it, or let it go?', category: 'conflict', emoji: '💬', themes: ['conflict', 'community'] },
  { text: 'What is a strong opinion you have changed your mind about in the last year?', category: 'changing your mind', emoji: '🔄', themes: ['growth', 'learning'] },
  { text: 'What does it look like when you are in flow? How would we spot it?', category: 'flow', emoji: '🌊', themes: ['work', 'craft'] },
  { text: 'What is the fastest way to lose your buy-in on a project?', category: 'commitment', emoji: '🚪', themes: ['values', 'work'] },
  { text: 'Would you rather be told the hard thing immediately or once someone has a fix in mind?', category: 'feedback', emoji: '📣', themes: ['conflict', 'connection'] },
  { text: 'What is a rule everyone follows that you think is nonsense?', category: 'brules', emoji: '🧨', themes: ['values', 'boundaries'] },
  { text: 'What is the last thing you shipped that you were genuinely proud of?', category: 'craft', emoji: '🏗️', themes: ['craft', 'creativity'] },
  { text: 'What part of your work would you automate tomorrow if you could?', category: 'leverage', emoji: '⚙️', themes: ['work', 'rest'] },
  { text: 'What do you do first when something breaks in production?', category: 'under pressure', emoji: '🚨', themes: ['work', 'courage'] },
  { text: 'What is a mistake you made that you would happily make again?', category: 'good failures', emoji: '🎯', themes: ['memory', 'growth'] },
  { text: 'When you are stuck, do you go quiet, go for a walk, or go ask someone?', category: 'getting unstuck', emoji: '🧗', themes: ['work', 'comfort', 'rest'] },
  { text: 'Whose work do you quietly study?', category: 'influences', emoji: '🔭', themes: ['learning', 'craft'] },
  { text: 'What is the smallest change that made the biggest difference to how you work?', category: 'small hinges', emoji: '🔑', themes: ['work', 'growth'] },
  { text: 'What would you want us to do if you went quiet for a week?', category: 'looking out', emoji: '🫱', themes: ['community', 'connection'] },
  { text: 'What do you need from a meeting for it to have been worth your time?', category: 'meetings', emoji: '⏱️', themes: ['work', 'boundaries'] },
  { text: 'What is your honest tell that you are overloaded?', category: 'capacity', emoji: '🪫', themes: ['rest', 'boundaries'] },
  { text: 'What is a problem you would work on for free?', category: 'obsession', emoji: '🔥', themes: ['work', 'play'] },
  { text: 'Where does your gut usually beat your analysis, and where does it usually lose?', category: 'fast and slow', emoji: '🧠', themes: ['identity', 'learning'] },
  { text: 'What is something you believe about AI that most people you talk to do not?', category: 'contrarian', emoji: '🤖', themes: ['values', 'identity'] },
  { text: 'What is the part of building with AI you find genuinely hard?', category: 'honest difficulty', emoji: '🪛', themes: ['learning', 'craft'] },
  { text: 'What do you want to be noticeably better at six months from now?', category: 'growth', emoji: '📈', themes: ['growth', 'ambition'] },
  { text: 'What does a good week look like for you, hour by hour?', category: 'ideal week', emoji: '🗓️', themes: ['ritual', 'rest', 'work'] },
  { text: 'What kind of praise actually lands for you?', category: 'recognition', emoji: '👏', themes: ['connection', 'identity'] },
  { text: 'What is a question you wish clients asked you more often?', category: 'client work', emoji: '💼', themes: ['work', 'craft'] },
  { text: 'When has quitting something been the right call?', category: 'knowing when', emoji: '🛑', themes: ['boundaries', 'growth'] },
  { text: 'What do you want to be the person we come to for?', category: 'your lane', emoji: '🧭', themes: ['identity', 'generosity'] },
  { text: 'What is the most useful thing you learned the hard way?', category: 'scar tissue', emoji: '🩹', themes: ['learning', 'growth'] },
  { text: 'Would you rather ship it rough on Friday or right on Wednesday next week?', category: 'shipping', emoji: '🚀', themes: ['craft', 'values'] },
  { text: 'What is one thing about how you work that people usually get wrong at first?', category: 'user manual', emoji: '📖', themes: ['identity', 'connection'] },
  { text: 'What are you working on that you would love a second pair of eyes on?', category: 'open invitation', emoji: '👀', themes: ['work', 'community'] },
  { text: 'What would make this crew worth staying in five years from now?', category: 'the long game', emoji: '🌳', themes: ['community', 'values'] },

  // ── 32 onward: drafted 2026-08-12. Draft for Nat to read in the app. ──

  // Trust, and showing people your work
  { text: 'Who was the first person you ever showed something you built, and how did that go?', category: 'first reveal', emoji: '🫣', themes: ['memory', 'courage'] },
  { text: 'Would you rather demo something half-built or describe something finished?', category: 'demo day', emoji: '🎬', themes: ['courage', 'craft'] },
  { text: 'What would you build in public if embarrassment were off the table?', category: 'building in public', emoji: '🏗️', themes: ['courage', 'ambition'] },
  { text: 'What makes it easy for you to say "I don\'t know" out loud?', category: 'not knowing', emoji: '🤷', themes: ['courage', 'values'] },
  { text: 'What is a question you were scared to ask that turned out completely fine?', category: 'asked anyway', emoji: '🙋', themes: ['courage', 'learning'] },
  { text: 'Whose "looks good to me" means the most to you?', category: 'lgtm', emoji: '✅', themes: ['connection', 'craft'] },
  { text: 'Do you trust someone faster when they admit a mistake or when they catch one of yours?', category: 'trust signals', emoji: '🤝', themes: ['connection', 'values'] },
  { text: 'What is something you double-check even when nobody would ever notice?', category: 'quiet diligence', emoji: '🔍', themes: ['craft', 'values'] },
  { text: 'When has asking for help early saved you a week?', category: 'ask early', emoji: '🛟', themes: ['learning', 'connection'] },
  { text: 'What is a generous assumption you try to make about other people\'s code?', category: 'generous reads', emoji: '🤲', themes: ['generosity', 'craft'] },
  { text: 'What is the kindest thing anyone has done during your worst bug?', category: 'bug kindness', emoji: '💛', themes: ['connection', 'memory'] },
  { text: 'Would you rather work with someone brilliant and prickly or steady and kind?', category: 'who you build with', emoji: '⚖️', themes: ['values', 'community'] },
  { text: 'What makes you feel safe enough to think out loud in a group?', category: 'thinking out loud', emoji: '💭', themes: ['community', 'comfort'] },
  { text: 'What is the first thing you notice about how a team treats its newest person?', category: 'new person test', emoji: '🌱', themes: ['community', 'values'] },
  { text: 'What is something you would rather confess badly now than perfectly later?', category: 'confess early', emoji: '📢', themes: ['courage', 'values'] },
  { text: 'How do you like to be told your work has a problem?', category: 'breaking it to you', emoji: '📨', themes: ['conflict', 'connection'] },
  { text: 'What did a great teammate once do that you have copied ever since?', category: 'copied kindness', emoji: '📋', themes: ['learning', 'community'] },
  { text: 'Would you rather have your work watched while you do it, or reviewed after?', category: 'over the shoulder', emoji: '🪟', themes: ['boundaries', 'identity'] },

  // Disagreement, and coming back from it
  { text: 'What is a disagreement you actually enjoyed?', category: 'good arguments', emoji: '🥊', themes: ['conflict', 'play'] },
  { text: 'How can someone tell the difference between you debating and you upset?', category: 'debate vs upset', emoji: '🌡️', themes: ['conflict', 'identity'] },
  { text: 'What is your favorite way to lose an argument?', category: 'losing well', emoji: '🏳️', themes: ['conflict', 'growth'] },
  { text: 'Would you rather be talked out of a bad idea gently or bluntly?', category: 'talked out of it', emoji: '🧯', themes: ['conflict', 'connection'] },
  { text: 'What is a phrase that instantly lowers the temperature for you?', category: 'cooling words', emoji: '🧊', themes: ['conflict', 'comfort'] },
  { text: 'What is a hill you used to die on that you have quietly walked down from?', category: 'abandoned hills', emoji: '⛰️', themes: ['growth', 'humour'] },
  { text: 'When someone pushes back on your work, what is your honest first feeling?', category: 'first pushback', emoji: '🫀', themes: ['conflict', 'identity'] },
  { text: 'What kind of disagreement is worth slowing a whole project down for?', category: 'worth the delay', emoji: '🚧', themes: ['values', 'conflict'] },
  { text: 'How do you repair things after a tense conversation about work?', category: 'after the tension', emoji: '🪡', themes: ['conflict', 'connection'] },
  { text: 'Would you rather be wrong loudly and corrected fast, or right quietly and never noticed?', category: 'loud and wrong', emoji: '📻', themes: ['courage', 'identity'] },
  { text: 'What is a criticism that stung because it was true?', category: 'true sting', emoji: '🐝', themes: ['growth', 'memory'] },
  { text: 'What is something you pretend to be easygoing about but secretly are not?', category: 'secretly picky', emoji: '🎭', themes: ['humour', 'identity'] },
  { text: 'What do you do when two people you respect disagree with each other?', category: 'caught between', emoji: '🪢', themes: ['conflict', 'community'] },
  { text: 'What is the most productive fight a project of yours ever had?', category: 'productive fights', emoji: '⚡', themes: ['conflict', 'work'] },

  // Committing, following through, finishing
  { text: 'What helps you commit to a plan you argued against?', category: 'disagree and commit', emoji: '🤝', themes: ['values', 'community'] },
  { text: 'What is your relationship with deadlines — fuel, background noise, or dread?', category: 'deadline feelings', emoji: '⏰', themes: ['work', 'identity'] },
  { text: 'What is the last thing you finished purely because you said you would?', category: 'kept word', emoji: '📜', themes: ['values', 'work'] },
  { text: 'Would you rather over-promise and scramble or under-promise and coast?', category: 'promise sizing', emoji: '📏', themes: ['work', 'values'] },
  { text: 'What does the last ten percent of a project feel like for you?', category: 'the last mile', emoji: '🏁', themes: ['work', 'craft'] },
  { text: 'What is a project you abandoned that still waves at you sometimes?', category: 'the one that waves', emoji: '👋', themes: ['memory', 'creativity'] },
  { text: 'What helps you stay honest about whether something is actually done?', category: 'done means done', emoji: '🎯', themes: ['craft', 'values'] },
  { text: 'Who is allowed to check on your progress without it feeling like nagging?', category: 'welcome check-ins', emoji: '📬', themes: ['connection', 'boundaries'] },
  { text: 'What is a tiny public commitment you could make this week?', category: 'say it out loud', emoji: '📣', themes: ['courage', 'community'] },
  { text: 'When do you decide a draft is good enough to show?', category: 'good enough', emoji: '🚦', themes: ['craft', 'courage'] },
  { text: 'What is something you finish fast and something you finish slow?', category: 'fast and slow finisher', emoji: '🐇', themes: ['work', 'identity'] },
  { text: 'What was the best deadline you ever missed?', category: 'best missed deadline', emoji: '🗓️', themes: ['humour', 'memory'] },
  { text: 'Do you work better with a scoreboard or without one?', category: 'scoreboards', emoji: '🧮', themes: ['work', 'identity'] },
  { text: 'What result are you chasing right now that would be worth a hard month?', category: 'worth a hard month', emoji: '🥇', themes: ['ambition', 'work'] },

  // How your head works
  { text: 'Do you think best while talking, writing, walking, or staring at a wall?', category: 'thinking medium', emoji: '🚶', themes: ['identity', 'learning'] },
  { text: 'What is a snap judgment you make that is almost always right?', category: 'good instincts', emoji: '⚡', themes: ['identity', 'learning'] },
  { text: 'What is a snap judgment you make that you have learned not to trust?', category: 'bad instincts', emoji: '🚩', themes: ['learning', 'growth'] },
  { text: 'When you are stuck, do you want a rubber duck or a whiteboard?', category: 'duck or whiteboard', emoji: '🦆', themes: ['work', 'learning'] },
  { text: 'Would you rather decide with too little information or too much?', category: 'information diet', emoji: '📊', themes: ['identity', 'work'] },
  { text: 'What decision do you always overthink even though it never matters?', category: 'overthought trifles', emoji: '🌀', themes: ['humour', 'identity'] },
  { text: 'What big decision did you once make embarrassingly fast — and was it right?', category: 'fast big calls', emoji: '🎲', themes: ['memory', 'courage'] },
  { text: 'Do your best ideas arrive in the shower, on a walk, mid-conversation, or at 2am?', category: 'idea weather', emoji: '💡', themes: ['creativity', 'identity'] },
  { text: 'What do you do with an idea that arrives at the worst possible time?', category: 'inconvenient ideas', emoji: '📝', themes: ['creativity', 'ritual'] },
  { text: 'Are you more likely to miss the forest or the trees?', category: 'forest or trees', emoji: '🌲', themes: ['identity', 'learning'] },
  { text: 'What is a mental model you reach for constantly?', category: 'pocket models', emoji: '🧰', themes: ['learning', 'craft'] },
  { text: 'What kind of problem makes your brain light up before you even choose to care?', category: 'brain candy', emoji: '🍬', themes: ['play', 'identity'] },
  { text: 'What kind of problem makes your brain fold its arms and refuse?', category: 'brain strike', emoji: '🙅', themes: ['identity', 'boundaries'] },
  { text: 'Would you rather be great at asking questions or great at answering them?', category: 'ask or answer', emoji: '❓', themes: ['learning', 'identity'] },
  { text: 'When did changing your mind in public cost you nothing and teach you a lot?', category: 'public mind change', emoji: '🔄', themes: ['courage', 'growth'] },
  { text: 'What do you do differently when you know you are tired?', category: 'tired brain rules', emoji: '😴', themes: ['rest', 'craft'] },
  { text: 'What is a belief you hold at 90% that most people hold at 100%?', category: 'held loosely', emoji: '🎈', themes: ['values', 'learning'] },
  { text: 'Do you trust a plan more when it is detailed or when it is short?', category: 'plan taste', emoji: '🗺️', themes: ['work', 'identity'] },
  { text: 'What is the most useful dumb question you have ever asked?', category: 'dumb questions', emoji: '🐣', themes: ['learning', 'humour'] },
  { text: 'When you estimate how long something will take, what is your honest multiplier?', category: 'estimate honesty', emoji: '✖️', themes: ['work', 'humour'] },
  { text: 'What is a coin-flip decision you secretly wanted the coin to decide?', category: 'let the coin call it', emoji: '🪙', themes: ['identity', 'humour'] },
  { text: 'What is something you only understood once you drew it?', category: 'drawn to understand', emoji: '✏️', themes: ['learning', 'creativity'] },
  { text: 'Would you rather your thinking be faster or your rethinking be easier?', category: 'think vs rethink', emoji: '♻️', themes: ['growth', 'learning'] },
  { text: 'What is a pattern you notice everywhere now that you have seen it once?', category: 'pattern glasses', emoji: '👓', themes: ['learning', 'play'] },

  // How ideas travel, and the people who carry them
  { text: 'Are you the one who finds things, the one who connects people, or the one who convinces the room?', category: 'connector maven closer', emoji: '🕸️', themes: ['identity', 'community'] },
  { text: 'What is the last thing you recommended so hard that someone actually tried it?', category: 'evangelist moment', emoji: '📢', themes: ['generosity', 'play'] },
  { text: 'Who in your life hears about your discoveries first?', category: 'first to hear', emoji: '📞', themes: ['connection', 'play'] },
  { text: 'What made the best explanation you ever heard stick?', category: 'sticky explanations', emoji: '🧲', themes: ['learning', 'craft'] },
  { text: 'What is an idea you adopted late and now cannot imagine living without?', category: 'late adopter wins', emoji: '🐢', themes: ['growth', 'humour'] },
  { text: 'What is something you tried purely because the wrong person recommended it?', category: 'unlikely source', emoji: '🎁', themes: ['memory', 'play'] },
  { text: 'Would you rather introduce two strangers or be introduced by one?', category: 'the introducer', emoji: '🔗', themes: ['connection', 'community'] },
  { text: 'What tiny change once tipped a whole project from stuck to moving?', category: 'tipping points', emoji: '🎢', themes: ['work', 'memory'] },
  { text: 'What do you always do when someone tells you their name?', category: 'name keeping', emoji: '🏷️', themes: ['connection', 'ritual'] },
  { text: 'What is the most contagious enthusiasm you have ever caught from someone?', category: 'caught enthusiasm', emoji: '🤩', themes: ['connection', 'memory'] },
  { text: 'What deserves to spread further than it has?', category: 'underrated things', emoji: '🌬️', themes: ['values', 'generosity'] },
  { text: 'How do you win over the one skeptic in the room?', category: 'the skeptic', emoji: '🧲', themes: ['conflict', 'craft'] },
  { text: 'What is a community you watched come alive, and what lit it?', category: 'watched it ignite', emoji: '🔥', themes: ['community', 'memory'] },
  { text: 'Do you learn about new tools from friends, feeds, or falling down rabbit holes?', category: 'discovery channel', emoji: '🐇', themes: ['learning', 'identity'] },
  { text: 'What is a trend you called early and never got credit for?', category: 'called it', emoji: '🔮', themes: ['humour', 'identity'] },
  { text: 'What is a trend you resisted and were completely wrong about?', category: 'resisted it', emoji: '🙈', themes: ['humour', 'growth'] },

  // Energy, quiet, and where your battery lives
  { text: 'After a full day with people, what do you need?', category: 'social battery', emoji: '🔋', themes: ['rest', 'identity'] },
  { text: 'Do you do your best work with people around, or completely alone?', category: 'alone or around', emoji: '🏝️', themes: ['work', 'identity'] },
  { text: 'What is your version of closing the office door?', category: 'the closed door', emoji: '🚪', themes: ['boundaries', 'ritual'] },
  { text: 'In a group conversation, are you the first voice, the last voice, or the follow-up message?', category: 'when you speak', emoji: '🎙️', themes: ['identity', 'community'] },
  { text: 'What do people mistake for shyness or aloofness in you that is actually something else?', category: 'misread quiet', emoji: '🌫️', themes: ['identity', 'connection'] },
  { text: 'What kind of noise helps you work, and what kind ruins you?', category: 'noise diet', emoji: '🎧', themes: ['work', 'comfort'] },
  { text: 'Would you rather present to fifty strangers or make small talk with five?', category: 'stage or mingle', emoji: '🎤', themes: ['identity', 'courage'] },
  { text: 'What social thing do people assume drains you but actually feeds you?', category: 'surprise fuel', emoji: '⛽', themes: ['identity', 'connection'] },
  { text: 'How long can you happily go without speaking to another human?', category: 'quiet capacity', emoji: '🤫', themes: ['rest', 'humour'] },
  { text: 'What does your calendar look like in your ideal week — packed, dotted, or empty?', category: 'calendar shape', emoji: '📅', themes: ['rest', 'boundaries'] },
  { text: 'What is the deepest you have ever concentrated, and what made it possible?', category: 'deepest focus', emoji: '🕳️', themes: ['work', 'memory'] },
  { text: 'What reliably breaks your concentration, and what reliably protects it?', category: 'focus fences', emoji: '⛩️', themes: ['work', 'boundaries'] },
  { text: 'Are you a camera-on or camera-off person, honestly?', category: 'camera truth', emoji: '📷', themes: ['identity', 'humour'] },
  { text: 'What time of day is your brain actually open for business?', category: 'brain hours', emoji: '🕰️', themes: ['work', 'ritual'] },
  { text: 'What is your favorite way to be together with people without talking?', category: 'parallel company', emoji: '🧶', themes: ['connection', 'rest'] },
  { text: 'When you cancel plans, what is it usually protecting?', category: 'the real reason', emoji: '🛡️', themes: ['boundaries', 'rest'] },
  { text: 'What does an empty afternoon do to you — calm you or unsettle you?', category: 'empty afternoons', emoji: '🌤️', themes: ['rest', 'identity'] },
  { text: 'Where do you go, physically or mentally, to hear yourself think?', category: 'thinking place', emoji: '⛰️', themes: ['place', 'rest'] },

  // Range — the roads that led you here
  { text: 'What did you want to be at age ten, and what survived of that?', category: 'age ten plan', emoji: '🧒', themes: ['memory', 'identity'] },
  { text: 'What job have you had that sounds nothing like what you do now but secretly trained you for it?', category: 'secret training', emoji: '🎓', themes: ['memory', 'work'] },
  { text: 'What is a skill from a hobby that sneaks into your work constantly?', category: 'hobby crossover', emoji: '🎨', themes: ['creativity', 'craft'] },
  { text: 'Would you rather be dangerous at ten things or world-class at one?', category: 'range or depth', emoji: '📐', themes: ['identity', 'ambition'] },
  { text: 'What is the most useful detour your life has taken?', category: 'useful detours', emoji: '🛤️', themes: ['memory', 'growth'] },
  { text: 'What is something you learned in a completely different field that engineers should steal?', category: 'steal this idea', emoji: '🧳', themes: ['learning', 'creativity'] },
  { text: 'What were you doing five years ago, and what would that person think of this?', category: 'five years back', emoji: '⏪', themes: ['memory', 'growth'] },
  { text: 'What is a subject you know weirdly well for no professional reason?', category: 'useless expertise', emoji: '🦉', themes: ['learning', 'play'] },
  { text: 'What is a sport, instrument, or craft that taught you how you practice?', category: 'how you practice', emoji: '🎻', themes: ['learning', 'ritual'] },
  { text: 'If you had to leave tech tomorrow, what would you go do?', category: 'the other life', emoji: '🌾', themes: ['identity', 'ambition'] },
  { text: 'What is a class you took that seemed pointless and turned out to matter?', category: 'pointless class', emoji: '🏫', themes: ['memory', 'learning'] },
  { text: 'What did your first real project teach you that no course could?', category: 'first project', emoji: '🐛', themes: ['memory', 'learning'] },
  { text: 'What is a tool from another trade you wish software had?', category: 'borrowed tools', emoji: '🔧', themes: ['creativity', 'craft'] },
  { text: 'Which of your past selves would be best to pair with on today\'s problem?', category: 'past self pairing', emoji: '👥', themes: ['identity', 'play'] },
  { text: 'What is something you quit that you are glad you tried?', category: 'glad i tried', emoji: '🚪', themes: ['memory', 'growth'] },
  { text: 'What is the least likely place you have ever solved a work problem?', category: 'unlikely desk', emoji: '🛁', themes: ['place', 'humour'] },
  { text: 'What is a book far outside tech that changed how you build?', category: 'outside books', emoji: '📚', themes: ['learning', 'creativity'] },
  { text: 'What would you study for a year if money and usefulness did not matter?', category: 'pure curiosity', emoji: '🔭', themes: ['learning', 'play'] },

  // What actually drives you
  { text: 'Autonomy, mastery, or purpose — which one, missing, makes you quit?', category: 'the dealbreaker', emoji: '🧨', themes: ['values', 'work'] },
  { text: 'What is a task you would do worse if someone paid you more for it?', category: 'paid worse', emoji: '💸', themes: ['values', 'humour'] },
  { text: 'When did you last lose track of time on purpose?', category: 'time lost well', emoji: '⌛', themes: ['play', 'work'] },
  { text: 'What part of your work would you keep doing after winning the lottery?', category: 'lottery test', emoji: '🎰', themes: ['values', 'identity'] },
  { text: 'Do you push harder for a goal, a person, or a streak?', category: 'what pulls you', emoji: '🧲', themes: ['identity', 'ambition'] },
  { text: 'What is the most motivating sentence anyone has said to you?', category: 'the sentence', emoji: '💬', themes: ['memory', 'connection'] },
  { text: 'What is the most de-motivating sentence anyone has said to you?', category: 'the anti-sentence', emoji: '🥀', themes: ['memory', 'boundaries'] },
  { text: 'Would you rather own the outcome or own the process?', category: 'outcome or process', emoji: '🎛️', themes: ['work', 'identity'] },
  { text: 'What makes a task feel like yours instead of assigned?', category: 'making it yours', emoji: '🖊️', themes: ['work', 'values'] },
  { text: 'What is a skill you practice with no goal at all?', category: 'practice for nothing', emoji: '🪁', themes: ['play', 'craft'] },
  { text: 'Whose approval are you honestly still building for?', category: 'the invisible judge', emoji: '🪞', themes: ['identity', 'memory'] },
  { text: 'What would you make if nobody could ever see it?', category: 'audience of none', emoji: '🌑', themes: ['creativity', 'identity'] },
  { text: 'What is the difference between a job you survive and a job you love, in one detail?', category: 'one detail', emoji: '🔬', themes: ['values', 'work'] },
  { text: 'What streak are you currently protecting?', category: 'streaks', emoji: '🔥', themes: ['ritual', 'play'] },

  // Listening, and getting to yes
  { text: 'What do you repeat back to make sure you actually heard someone?', category: 'mirroring', emoji: '🪞', themes: ['connection', 'craft'] },
  { text: 'What is the best question anyone ever asked you in an interview, on either side of the table?', category: 'interview keeper', emoji: '🎙️', themes: ['memory', 'work'] },
  { text: 'How do you say no to good ideas so the best one fits?', category: 'no to good', emoji: '🚫', themes: ['boundaries', 'craft'] },
  { text: 'What is your move when a conversation is going in circles?', category: 'circle breaker', emoji: '🌀', themes: ['craft', 'conflict'] },
  { text: 'Would you rather negotiate for yourself or for someone else?', category: 'whose corner', emoji: '🥊', themes: ['identity', 'generosity'] },
  { text: 'What is a time "no" was the beginning of the conversation, not the end?', category: 'no as a door', emoji: '🚪', themes: ['memory', 'conflict'] },
  { text: 'What do people tell you that they say they have never told anyone?', category: 'safe ears', emoji: '🗝️', themes: ['connection', 'identity'] },
  { text: 'What is a label someone put on your feelings that instantly helped?', category: 'named feelings', emoji: '🏷️', themes: ['connection', 'memory'] },
  { text: 'When has silence done your negotiating for you?', category: 'strategic silence', emoji: '🤐', themes: ['craft', 'humour'] },
  { text: 'What is something you always ask for that most people just accept?', category: 'always ask', emoji: '🙋', themes: ['courage', 'humour'] },
  { text: 'How do you disagree with someone you badly want to like you?', category: 'delicate no', emoji: '🌷', themes: ['conflict', 'connection'] },
  { text: 'What is your tell when you are about to cave?', category: 'the cave tell', emoji: '🫠', themes: ['humour', 'identity'] },

  // The long haul — grit, crews, and boats
  { text: 'What is the longest you have kept working on something with no sign it would work?', category: 'faith miles', emoji: '🏜️', themes: ['courage', 'memory'] },
  { text: 'What is your version of the crew all rowing in time — when has a team just clicked?', category: 'swing', emoji: '🚣', themes: ['community', 'memory'] },
  { text: 'Would you rather a hard season with a great team or an easy season with a bad one?', category: 'hard with good people', emoji: '⛰️', themes: ['community', 'values'] },
  { text: 'What kept you going the last time everything said stop?', category: 'the keep-going thing', emoji: '🕯️', themes: ['courage', 'identity'] },
  { text: 'What is the scrappiest thing you have ever done to keep a project alive?', category: 'scrappy saves', emoji: '🩹', themes: ['memory', 'creativity'] },
  { text: 'What is a slow, unglamorous investment that quietly pays you every day?', category: 'quiet compounding', emoji: '🌱', themes: ['ritual', 'growth'] },
  { text: 'Who believed in a project of yours before it deserved it?', category: 'early believer', emoji: '🌟', themes: ['memory', 'connection'] },
  { text: 'What is the difference between stubborn and committed, in your own life?', category: 'stubborn or committed', emoji: '🪨', themes: ['values', 'identity'] },
  { text: 'What would you attempt if you knew it would take ten years?', category: 'ten year swing', emoji: '🌳', themes: ['ambition', 'courage'] },
  { text: 'What is a hardship that turned into your favorite story?', category: 'hardship story', emoji: '📖', themes: ['memory', 'humour'] },
  { text: 'When has being the least experienced person in the room been your advantage?', category: 'beginner advantage', emoji: '🐣', themes: ['courage', 'learning'] },
  { text: 'What do you do on the days the work does not love you back?', category: 'loveless days', emoji: '🌧️', themes: ['comfort', 'work'] },
  { text: 'What race are you running that only you can see?', category: 'invisible race', emoji: '🏃', themes: ['ambition', 'identity'] },
  { text: 'What is something you built that outlived the reason you built it?', category: 'outlived its reason', emoji: '🏛️', themes: ['memory', 'craft'] },

  // Designing your time
  { text: 'What would you stop doing entirely if nobody would find out?', category: 'quiet quit list', emoji: '🗑️', themes: ['boundaries', 'humour'] },
  { text: 'What is the 20% of your work that produces most of the good stuff?', category: 'the vital few', emoji: '🎯', themes: ['work', 'craft'] },
  { text: 'If you took a month completely off, what would you do in week three?', category: 'week three', emoji: '🏖️', themes: ['rest', 'play'] },
  { text: 'What is a recurring task you deleted and never missed?', category: 'deleted and free', emoji: '✂️', themes: ['boundaries', 'work'] },
  { text: 'Would you rather work four focused hours or eight loose ones?', category: 'four or eight', emoji: '⏳', themes: ['work', 'rest'] },
  { text: 'What do you batch, and what do you refuse to batch?', category: 'batching', emoji: '📦', themes: ['ritual', 'work'] },
  { text: 'What is the best thing you ever did with time an automation gave back?', category: 'time refund', emoji: '🎁', themes: ['rest', 'play'] },
  { text: 'What is your relationship with your inbox — inbox zero, inbox thousands, or inbox denial?', category: 'inbox truth', emoji: '📥', themes: ['humour', 'identity'] },
  { text: 'What tiny chore do you do immediately so it never becomes a task?', category: 'two minute rule', emoji: '⚡', themes: ['ritual', 'work'] },
  { text: 'What would a mini-retirement look like for you — one month, anywhere, no laptop?', category: 'mini retirement', emoji: '🧳', themes: ['rest', 'place'] },
  { text: 'What is something you check far more often than it changes?', category: 'over-checking', emoji: '🔄', themes: ['humour', 'ritual'] },
  { text: 'What is one meeting in your life that should have been a message, and one message that should have been a meeting?', category: 'meeting or message', emoji: '📮', themes: ['work', 'humour'] },

  // Building with AI
  { text: 'What did an AI do this week that genuinely surprised you?', category: 'weekly surprise', emoji: '🤖', themes: ['learning', 'play'] },
  { text: 'What do you still refuse to let an AI touch?', category: 'hands off', emoji: '🖐️', themes: ['boundaries', 'craft'] },
  { text: 'What was the moment AI went from toy to tool for you?', category: 'toy to tool', emoji: '🔨', themes: ['memory', 'work'] },
  { text: 'Do you talk to your AI politely, bluntly, or like a slightly dim genie?', category: 'prompt manners', emoji: '🧞', themes: ['humour', 'identity'] },
  { text: 'What is your favorite job to hand an agent and walk away from?', category: 'fire and forget', emoji: '🚶', themes: ['work', 'rest'] },
  { text: 'What is the worst thing an AI has confidently told you?', category: 'confident nonsense', emoji: '🎩', themes: ['humour', 'learning'] },
  { text: 'How do you check work you did not do yourself?', category: 'trust but verify', emoji: '🔍', themes: ['craft', 'values'] },
  { text: 'What has building with AI taught you about how you explain things?', category: 'explaining better', emoji: '🗣️', themes: ['learning', 'craft'] },
  { text: 'Would you rather have an AI that is brilliant but weird, or reliable but plain?', category: 'brilliant or reliable', emoji: '⚗️', themes: ['identity', 'values'] },
  { text: 'What is a task you were sure AI could not do until it did?', category: 'proved wrong', emoji: '😮', themes: ['growth', 'learning'] },
  { text: 'What skill of yours got MORE valuable when AI arrived?', category: 'worth more now', emoji: '💎', themes: ['identity', 'craft'] },
  { text: 'What do you know now about working with agents that you wish someone had told you on day one?', category: 'day one advice', emoji: '📜', themes: ['learning', 'generosity'] },
  { text: 'When an agent goes off the rails, do you correct it, restart it, or take over?', category: 'off the rails', emoji: '🚂', themes: ['work', 'identity'] },
  { text: 'What is the most human thing you have caught yourself doing toward a machine?', category: 'too human', emoji: '💌', themes: ['humour', 'connection'] },
  { text: 'What part of your taste can you not seem to teach a model?', category: 'unteachable taste', emoji: '👅', themes: ['craft', 'identity'] },
  { text: 'How has AI changed what you consider a waste of your time?', category: 'new waste line', emoji: '📉', themes: ['values', 'work'] },
  { text: 'What would you build this month if agents were free and tireless?', category: 'free and tireless', emoji: '🏗️', themes: ['ambition', 'creativity'] },
  { text: 'What is your honest ratio of prompting to fixing?', category: 'prompt to fix ratio', emoji: '⚖️', themes: ['humour', 'craft'] },
  { text: 'Do you name your agents, and what does that say about you?', category: 'naming the robots', emoji: '🏷️', themes: ['play', 'identity'] },
  { text: 'What is a question you would love to ask a model that remembers everything you ever built?', category: 'the archive question', emoji: '🗄️', themes: ['memory', 'creativity'] },
  { text: 'What did you unlearn to get good at building with AI?', category: 'unlearning', emoji: '🧹', themes: ['growth', 'learning'] },
  { text: 'Where do you draw the line between help and homework someone else did?', category: 'whose work is it', emoji: '📝', themes: ['values', 'identity'] },
  { text: 'What is the smallest AI win that made your actual day better?', category: 'small ai wins', emoji: '🌤️', themes: ['comfort', 'work'] },
  { text: 'What do you predict about AI for next year that we can check together?', category: 'checkable prediction', emoji: '📆', themes: ['play', 'community'] },
  { text: 'If your favorite model had a personality review, what would you write?', category: 'model review', emoji: '⭐', themes: ['humour', 'play'] },
  { text: 'What is a job you would trust an agent with for a stranger, but not for someone you love?', category: 'stakes and love', emoji: '❤️‍🩹', themes: ['values', 'connection'] },
  { text: 'What conversation with an AI has stuck with you longest?', category: 'the one that stuck', emoji: '📌', themes: ['memory', 'learning'] },
  { text: 'When do you feel most like a builder, and when most like a passenger?', category: 'builder or passenger', emoji: '🎢', themes: ['identity', 'craft'] },

  // The craft
  { text: 'What is your debugging ritual when the obvious things are all ruled out?', category: 'deep debugging', emoji: '🕵️', themes: ['craft', 'ritual'] },
  { text: 'What is the best bug you ever found — the one you still tell people about?', category: 'trophy bug', emoji: '🏆', themes: ['memory', 'humour'] },
  { text: 'Do you read the docs first, or press the buttons first?', category: 'docs or buttons', emoji: '📖', themes: ['learning', 'identity'] },
  { text: 'What is the naming decision you have argued about longest?', category: 'naming things', emoji: '🪧', themes: ['craft', 'humour'] },
  { text: 'What does clean mean to you — in code, in a kitchen, in anything?', category: 'clean means', emoji: '🧼', themes: ['craft', 'values'] },
  { text: 'What is a tool that earned its keep this week?', category: 'earned its keep', emoji: '🛠️', themes: ['craft', 'work'] },
  { text: 'What is a tool everyone loves that you just cannot?', category: 'cannot love it', emoji: '🥶', themes: ['humour', 'identity'] },
  { text: 'Comments, tests, or commit messages — which of your habits would embarrass you in public?', category: 'hygiene confession', emoji: '😳', themes: ['humour', 'craft'] },
  { text: 'What is the oldest thing you built that is still running somewhere?', category: 'still running', emoji: '🕰️', themes: ['memory', 'craft'] },
  { text: 'Would you rather inherit messy code with great docs or beautiful code with none?', category: 'inheritance choice', emoji: '📜', themes: ['craft', 'values'] },
  { text: 'What do you always do before you write a single line?', category: 'before the first line', emoji: '🧘', themes: ['ritual', 'craft'] },
  { text: 'How do you know when to stop polishing?', category: 'polish limit', emoji: '💅', themes: ['craft', 'boundaries'] },
  { text: 'What is a shortcut you take that you would defend to anyone?', category: 'proud shortcut', emoji: '🛣️', themes: ['craft', 'values'] },
  { text: 'What is a corner you cut once and paid for, for years?', category: 'expensive corner', emoji: '📐', themes: ['memory', 'learning'] },
  { text: 'What error message do you know by heart?', category: 'memorized error', emoji: '🚨', themes: ['humour', 'memory'] },
  { text: 'What is the most satisfying thing to delete?', category: 'joy of deletion', emoji: '🗑️', themes: ['craft', 'play'] },
  { text: 'Keyboard, mouse, or voice — where does your hand go when you think?', category: 'hands and thinking', emoji: '⌨️', themes: ['identity', 'ritual'] },
  { text: 'What is a piece of software whose feel you love, separate from what it does?', category: 'the feel of it', emoji: '🎹', themes: ['craft', 'play'] },
  { text: 'What detail do you notice in other people\'s work that almost nobody else does?', category: 'detail radar', emoji: '📡', themes: ['craft', 'identity'] },
  { text: 'What is your white whale — the thing you have tried to build more than twice?', category: 'white whale', emoji: '🐋', themes: ['ambition', 'memory'] },
  { text: 'Would you rather review code or have yours reviewed?', category: 'review direction', emoji: '🔁', themes: ['craft', 'identity'] },
  { text: 'What is the nicest thing anyone has written in a code review?', category: 'kind review', emoji: '💐', themes: ['connection', 'craft'] },
  { text: 'What do you do in the minute after you finally fix the impossible bug?', category: 'victory minute', emoji: '🎉', themes: ['ritual', 'play'] },
  { text: 'What is your relationship with TODO comments — promises, wishes, or lies?', category: 'todo truth', emoji: '📝', themes: ['humour', 'craft'] },
  { text: 'What have you built that you use every single day?', category: 'daily driver', emoji: '🚗', themes: ['craft', 'comfort'] },
  { text: 'What is something you keep hand-made even though a tool exists?', category: 'hand made anyway', emoji: '🧵', themes: ['craft', 'values'] },
  { text: 'When something is slow, do you profile it or guess first — honestly?', category: 'profile or guess', emoji: '🏎️', themes: ['humour', 'craft'] },
  { text: 'What is the best README, manual, or instructions you have ever read?', category: 'great instructions', emoji: '📘', themes: ['craft', 'learning'] },
  { text: 'What is a piece of your workflow you would defend like family?', category: 'sacred workflow', emoji: '🏰', themes: ['ritual', 'identity'] },
  { text: 'What is your favorite kind of problem: broken, slow, ugly, or confusing?', category: 'problem flavor', emoji: '🍽️', themes: ['craft', 'identity'] },
  { text: 'What would you never automate, purely because you enjoy doing it?', category: 'kept by choice', emoji: '🫖', themes: ['play', 'values'] },
  { text: 'What is the most over-engineered thing you have ever made, and do you regret it?', category: 'over-engineered', emoji: '🏗️', themes: ['humour', 'memory'] },

  // Learning, and being new at things
  { text: 'What are you learning right now, and what made you start?', category: 'currently learning', emoji: '🌱', themes: ['learning', 'growth'] },
  { text: 'Do you learn best from docs, videos, examples, or breaking things?', category: 'how you take it in', emoji: '🧪', themes: ['learning', 'identity'] },
  { text: 'What is the last rabbit hole that ate an evening, and was it worth it?', category: 'rabbit holes', emoji: '🕳️', themes: ['learning', 'play'] },
  { text: 'What do you do in the first ten minutes with a technology you have never touched?', category: 'first ten minutes', emoji: '⏲️', themes: ['learning', 'ritual'] },
  { text: 'What is something you understand deeply that took embarrassingly long to click?', category: 'slow click', emoji: '💡', themes: ['learning', 'humour'] },
  { text: 'Who explained something to you so well you still use their words?', category: 'borrowed words', emoji: '🗣️', themes: ['memory', 'learning'] },
  { text: 'What do you wish someone would just sit down and teach you?', category: 'teach me this', emoji: '🙏', themes: ['learning', 'community'] },
  { text: 'What could you teach this crew in twenty minutes with no slides?', category: 'twenty minute talk', emoji: '⏱️', themes: ['generosity', 'learning'] },
  { text: 'What is a fundamental you secretly never learned properly?', category: 'skipped fundamental', emoji: '🕳️', themes: ['humour', 'learning'] },
  { text: 'Would you rather understand why it works or just that it works?', category: 'why or that', emoji: '⚙️', themes: ['identity', 'learning'] },
  { text: 'What is the best mistake a student or junior ever caught you making?', category: 'caught by the new kid', emoji: '🎣', themes: ['humour', 'growth'] },
  { text: 'How do you take notes — and do you ever read them again?', category: 'note truth', emoji: '🗒️', themes: ['ritual', 'humour'] },
  { text: 'What is something you re-learn every single time you need it?', category: 'eternal relearning', emoji: '🔁', themes: ['humour', 'learning'] },
  { text: 'What did teaching someone else teach you about yourself?', category: 'teaching mirror', emoji: '🪞', themes: ['learning', 'identity'] },
  { text: 'What is a concept you finally got because of one perfect example?', category: 'the perfect example', emoji: '🎯', themes: ['learning', 'memory'] },
  { text: 'What subject could you listen to someone passionate talk about for an hour, knowing nothing?', category: 'passion listening', emoji: '👂', themes: ['connection', 'learning'] },
  { text: 'When you were last a total beginner, how did you treat yourself?', category: 'beginner self-talk', emoji: '🐥', themes: ['growth', 'comfort'] },
  { text: 'What is a skill you got good at faster than expected, and why do you think that was?', category: 'fast learner story', emoji: '🚀', themes: ['memory', 'learning'] },
  { text: 'What is the gap between what people assume you know and what you actually know?', category: 'assumed knowledge', emoji: '🌉', themes: ['identity', 'humour'] },
  { text: 'What question do you ask to find out how deep someone\'s knowledge really goes?', category: 'depth finder', emoji: '🎚️', themes: ['learning', 'craft'] },

  // A day at your desk
  { text: 'Describe your desk right now, honestly, no tidying first.', category: 'desk honesty', emoji: '🪑', themes: ['home', 'humour'] },
  { text: 'What is the first thing you open in the morning, and what does that say about you?', category: 'first open', emoji: '🌅', themes: ['ritual', 'identity'] },
  { text: 'How do you end a work day so it actually ends?', category: 'shutting down', emoji: '🌙', themes: ['ritual', 'rest'] },
  { text: 'What do you eat or drink while you work that is basically part of your setup?', category: 'desk fuel', emoji: '☕', themes: ['food', 'ritual'] },
  { text: 'What is on your walls where you work?', category: 'workspace walls', emoji: '🖼️', themes: ['home', 'identity'] },
  { text: 'Music with words, without words, or silence while you work?', category: 'work soundtrack', emoji: '🎵', themes: ['work', 'comfort'] },
  { text: 'What is your break style — walk, snack, scroll, or stare?', category: 'break style', emoji: '🚶', themes: ['rest', 'ritual'] },
  { text: 'What time do you do your worst work, and do you protect people from it?', category: 'worst hours', emoji: '🌘', themes: ['humour', 'boundaries'] },
  { text: 'What tiny upgrade to your workspace punched way above its weight?', category: 'small upgrade big win', emoji: '💺', themes: ['home', 'comfort'] },
  { text: 'One monitor, two monitors, or a laptop in a cafe?', category: 'screen setup', emoji: '🖥️', themes: ['work', 'identity'] },
  { text: 'What do you fidget with while you think?', category: 'thinking object', emoji: '🖇️', themes: ['ritual', 'comfort'] },
  { text: 'What is your honest tab count right now?', category: 'tab census', emoji: '🗂️', themes: ['humour', 'identity'] },
  { text: 'When you work from somewhere new, what is the first thing you need to feel settled?', category: 'portable home', emoji: '🎒', themes: ['place', 'comfort'] },
  { text: 'What do you wear when you do your best work?', category: 'work uniform', emoji: '🧦', themes: ['comfort', 'humour'] },
  { text: 'What is a ritual you do before hard work that is basically superstition?', category: 'work superstition', emoji: '🍀', themes: ['ritual', 'humour'] },
  { text: 'What app or site is your procrastination home base?', category: 'procrastination hq', emoji: '🏠', themes: ['humour', 'rest'] },
  { text: 'What does your ideal lunch break look like on a working day?', category: 'lunch design', emoji: '🥪', themes: ['food', 'rest'] },
  { text: 'Where were you sitting when you did the best work of your life so far?', category: 'best work spot', emoji: '📍', themes: ['place', 'memory'] },
  { text: 'What is the longest you have gone into the night for something you chose?', category: 'chosen all-nighter', emoji: '🌃', themes: ['memory', 'play'] },
  { text: 'How do you mark that it is the weekend, besides the calendar saying so?', category: 'weekend switch', emoji: '🎚️', themes: ['ritual', 'rest'] },
  { text: 'What is a sound from your workspace that would instantly relax you anywhere?', category: 'workspace sound', emoji: '⌨️', themes: ['comfort', 'place'] },
  { text: 'What would your desk plant say about how the month is going?', category: 'plant report', emoji: '🪴', themes: ['humour', 'home'] },

  // The human behind the keyboard
  { text: 'What was your first computer, and where did it live in your home?', category: 'first computer', emoji: '💾', themes: ['memory', 'home'] },
  { text: 'What was the first thing you ever made a computer do, and how did it feel?', category: 'first hello world', emoji: '👋', themes: ['memory', 'play'] },
  { text: 'What game have you sunk the most hours into across your whole life?', category: 'the big game', emoji: '🎮', themes: ['play', 'memory'] },
  { text: 'What did the internet sound like in your childhood home?', category: 'dial-up memories', emoji: '📠', themes: ['memory', 'home'] },
  { text: 'Who are you tech support for, and what do they think you do for a living?', category: 'family tech support', emoji: '📱', themes: ['family', 'humour'] },
  { text: 'What did your family make of what you do — then, and now?', category: 'explaining to family', emoji: '👪', themes: ['family', 'identity'] },
  { text: 'What piece of dead technology do you genuinely miss?', category: 'gone but loved', emoji: '🪦', themes: ['memory', 'comfort'] },
  { text: 'What sci-fi future did you grow up expecting that never arrived?', category: 'promised future', emoji: '🛸', themes: ['memory', 'play'] },
  { text: 'What sci-fi thing arrived in your lifetime that still feels impossible?', category: 'impossible arrived', emoji: '✨', themes: ['play', 'learning'] },
  { text: 'What is a website you loved that no longer exists?', category: 'lost websites', emoji: '🕸️', themes: ['memory', 'place'] },
  { text: 'What was your first screen name, and what were you thinking?', category: 'first screen name', emoji: '🕹️', themes: ['memory', 'humour'] },
  { text: 'What is a meal you have eaten a hundred times during crunch?', category: 'crunch food', emoji: '🍜', themes: ['food', 'memory'] },
  { text: 'What do you cook when you actually have time?', category: 'slow cooking', emoji: '🍲', themes: ['food', 'rest'] },
  { text: 'Where in the world would you most want to work for a month, laptop optional?', category: 'month elsewhere', emoji: '🌍', themes: ['place', 'ambition'] },
  { text: 'What is a completely offline thing you do to stay sane?', category: 'offline sanity', emoji: '🌲', themes: ['rest', 'ritual'] },
  { text: 'What is a movie or show about technology that gets it wonderfully wrong?', category: 'hollywood hacking', emoji: '🎬', themes: ['humour', 'play'] },
  { text: 'What fictional robot, AI, or computer did you grow up loving?', category: 'fictional machines', emoji: '🤖', themes: ['memory', 'play'] },
  { text: 'What did you build as a kid out of whatever was around?', category: 'kid builder', emoji: '🧱', themes: ['memory', 'creativity'] },
  { text: 'What is a physical skill you love precisely because it is nothing like your work?', category: 'hands not keys', emoji: '🪓', themes: ['play', 'rest'] },
  { text: 'What is your favorite tool that has no battery and no screen?', category: 'analog favorite', emoji: '🔦', themes: ['craft', 'comfort'] },
  { text: 'Who taught you to be curious?', category: 'curiosity roots', emoji: '🌳', themes: ['family', 'memory'] },
  { text: 'What is a place you have been that felt like the future?', category: 'felt like the future', emoji: '🏙️', themes: ['place', 'memory'] },
  { text: 'What is a place you have been that felt like stepping back fifty years, in the best way?', category: 'felt like the past', emoji: '🏚️', themes: ['place', 'comfort'] },
  { text: 'What was on your childhood bedroom walls?', category: 'bedroom walls', emoji: '🛏️', themes: ['memory', 'home'] },
  { text: 'What is a smell that means "late night working on something I love"?', category: 'late night smell', emoji: '🕯️', themes: ['memory', 'comfort'] },
  { text: 'What song can carry you through the most tedious task?', category: 'tedium anthem', emoji: '🎶', themes: ['comfort', 'work'] },
  { text: 'What do you do with your hands while something compiles, deploys, or loads?', category: 'waiting hands', emoji: '🫖', themes: ['ritual', 'humour'] },
  { text: 'What is your relationship with your phone before bed, honestly?', category: 'phone at night', emoji: '📵', themes: ['rest', 'humour'] },
  { text: 'What would teenage you think is the coolest part of your life now?', category: 'teenage verdict', emoji: '🛹', themes: ['memory', 'identity'] },
  { text: 'What is a small kindness a stranger on the internet once did for you?', category: 'internet kindness', emoji: '💌', themes: ['memory', 'generosity'] },

  // This crew
  { text: 'What is the best thing about building things with people you barely know yet?', category: 'strangers building', emoji: '🌉', themes: ['community', 'courage'] },
  { text: 'What would you want this crew to do together once a year, forever?', category: 'annual tradition', emoji: '🗓️', themes: ['community', 'ritual'] },
  { text: 'Show-and-tell, co-working, or a hard problem on a whiteboard — what should our next hour together be?', category: 'next hour', emoji: '🧑‍🏫', themes: ['community', 'play'] },
  { text: 'What is something you are building that this crew could genuinely move?', category: 'crew leverage', emoji: '🏋️', themes: ['work', 'community'] },
  { text: 'Would you rather this crew be your cheerleaders, your critics, or your co-founders?', category: 'crew role', emoji: '📣', themes: ['community', 'values'] },
  { text: 'What is a demo you would give if someone asked with zero notice?', category: 'zero notice demo', emoji: '🎪', themes: ['courage', 'craft'] },
  { text: 'What kind of help do you find easiest to offer a near-stranger?', category: 'easy offer', emoji: '🎁', themes: ['generosity', 'community'] },
  { text: 'What is a question you would love to ask everyone here, one by one?', category: 'ask the crew', emoji: '🎤', themes: ['connection', 'community'] },
  { text: 'What would make you message this group at midnight?', category: 'midnight message', emoji: '🌙', themes: ['community', 'play'] },
  { text: 'What is your favorite way to celebrate someone else\'s ship?', category: 'celebrating ships', emoji: '🚢', themes: ['generosity', 'play'] },
  { text: 'What should we absolutely not become as a group?', category: 'never become', emoji: '⛔', themes: ['values', 'community'] },
  { text: 'What is one thing you hope someone in this HIVE asks you about someday?', category: 'hoping to be asked', emoji: '🪝', themes: ['connection', 'identity'] },
  { text: 'What would a perfect first collaboration with someone here look like — small, real, finished?', category: 'first collab', emoji: '🤝', themes: ['community', 'work'] },
  { text: 'Whose answer to today\'s question are you most curious about?', category: 'curious about you', emoji: '👀', themes: ['connection', 'play'] },

  // The sillier ones
  { text: 'What is the most cursed keyboard shortcut, setting, or config you secretly love?', category: 'cursed favorite', emoji: '😈', themes: ['humour', 'craft'] },
  { text: 'Tabs or spaces — and more importantly, how strongly do you actually care?', category: 'the old war', emoji: '⚔️', themes: ['humour', 'play'] },
  { text: 'What would the error message for YOUR crash say?', category: 'personal error', emoji: '💥', themes: ['humour', 'identity'] },
  { text: 'What is the worst name you have ever given a file, folder, or variable that stuck forever?', category: 'final_v2_REAL', emoji: '📁', themes: ['humour', 'memory'] },
  { text: 'If your career had patch notes, what would this month\'s say?', category: 'patch notes', emoji: '🩹', themes: ['humour', 'growth'] },
  { text: 'What technology do you use daily and still low-key believe is magic?', category: 'still magic', emoji: '🪄', themes: ['play', 'humour'] },
  { text: 'What is your villain origin story as a user — the product moment that radicalized you?', category: 'user villain origin', emoji: '🦹', themes: ['humour', 'values'] },
  { text: 'What loading screen has held you hostage the longest?', category: 'held hostage', emoji: '⏳', themes: ['humour', 'memory'] },
  { text: 'If you got one system-wide undo for real life, how far back are you going?', category: 'life undo', emoji: '↩️', themes: ['humour', 'memory'] },
  { text: 'What would your autocomplete reveal about you?', category: 'autocomplete tell', emoji: '⌨️', themes: ['humour', 'identity'] },
  { text: 'Which fictional gadget would you actually use every day?', category: 'fictional gadget', emoji: '🔮', themes: ['play', 'humour'] },
  { text: 'What tech acronym did you confidently misunderstand for years?', category: 'acronym confession', emoji: '🔤', themes: ['humour', 'learning'] },
  { text: 'If this HIVE had a status page, what would your current status be?', category: 'status page', emoji: '🟢', themes: ['humour', 'community'] },
];
